CREATE TABLE `aurionGuildGovernanceStates` (
  `guildId` varchar(64) NOT NULL,
  `revision` bigint unsigned NOT NULL DEFAULT 0,
  `kingdomId` varchar(64) DEFAULT NULL,
  `capitalTerritoryId` varchar(128) DEFAULT NULL,
  `ruleSetVersion` varchar(96) NOT NULL,
  `contentVersion` varchar(96) NOT NULL,
  `updatedAt` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  CONSTRAINT `aurionGuildGovernanceStates_pk` PRIMARY KEY (`guildId`)
);--> statement-breakpoint
CREATE TABLE `aurionGuildCapabilityGrants` (
  `id` varchar(64) NOT NULL,
  `guildId` varchar(64) NOT NULL,
  `userId` int NOT NULL,
  `capability` enum('member_manage','diplomacy_manage','territory_manage','bank_deposit','bank_withdraw','building_manage','kingdom_consolidate') NOT NULL,
  `scopeKind` enum('guild','territory','kingdom','diplomacy','bank','building') NOT NULL,
  `scopeId` varchar(128) NOT NULL,
  `status` enum('active','revoked') NOT NULL DEFAULT 'active',
  `grantedByUserId` int NOT NULL,
  `grantReceiptId` varchar(64) NOT NULL,
  `idempotencyKey` varchar(128) NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT current_timestamp(),
  `updatedAt` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  CONSTRAINT `aurionGuildCapabilityGrants_pk` PRIMARY KEY (`id`),
  CONSTRAINT `aurionGuildCapabilityGrants_scope_uq` UNIQUE (`guildId`,`userId`,`capability`,`scopeKind`,`scopeId`),
  CONSTRAINT `aurionGuildCapabilityGrants_idempotency_uq` UNIQUE (`idempotencyKey`),
  INDEX `aurionGuildCapabilityGrants_user_status_idx` (`guildId`,`userId`,`status`)
);--> statement-breakpoint
CREATE TABLE `aurionGuildTerritories` (
  `territoryId` varchar(128) NOT NULL,
  `worldId` varchar(96) NOT NULL,
  `chunkX` int NOT NULL,
  `chunkZ` int NOT NULL,
  `guildId` varchar(64) NOT NULL,
  `state` enum('active','contested','released') NOT NULL DEFAULT 'active',
  `acquiredByUserId` int NOT NULL,
  `claimReceiptId` varchar(64) NOT NULL,
  `claimRevision` bigint unsigned NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT current_timestamp(),
  `updatedAt` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  CONSTRAINT `aurionGuildTerritories_pk` PRIMARY KEY (`territoryId`),
  CONSTRAINT `aurionGuildTerritories_world_chunk_uq` UNIQUE (`worldId`,`chunkX`,`chunkZ`),
  INDEX `aurionGuildTerritories_guild_state_idx` (`guildId`,`state`)
);--> statement-breakpoint
CREATE TABLE `aurionGuildKingdoms` (
  `id` varchar(64) NOT NULL,
  `guildId` varchar(64) NOT NULL,
  `name` varchar(64) NOT NULL,
  `rulerUserId` int NOT NULL,
  `capitalTerritoryId` varchar(128) NOT NULL,
  `territoryDigest` varchar(64) NOT NULL,
  `status` enum('active','dissolved') NOT NULL DEFAULT 'active',
  `revision` bigint unsigned NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT current_timestamp(),
  `updatedAt` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  CONSTRAINT `aurionGuildKingdoms_pk` PRIMARY KEY (`id`),
  CONSTRAINT `aurionGuildKingdoms_guild_uq` UNIQUE (`guildId`),
  CONSTRAINT `aurionGuildKingdoms_name_uq` UNIQUE (`name`)
);--> statement-breakpoint
CREATE TABLE `aurionGuildDiplomacyPacts` (
  `id` varchar(64) NOT NULL,
  `sourceGuildId` varchar(64) NOT NULL,
  `targetGuildId` varchar(64) NOT NULL,
  `pactType` enum('alliance','trade','non_aggression','tribute','sanction','war') NOT NULL,
  `status` enum('active','ended') NOT NULL DEFAULT 'active',
  `revision` bigint unsigned NOT NULL,
  `receiptId` varchar(64) NOT NULL,
  `idempotencyKey` varchar(128) NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT current_timestamp(),
  `updatedAt` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  CONSTRAINT `aurionGuildDiplomacyPacts_pk` PRIMARY KEY (`id`),
  CONSTRAINT `aurionGuildDiplomacyPacts_pair_type_uq` UNIQUE (`sourceGuildId`,`targetGuildId`,`pactType`),
  CONSTRAINT `aurionGuildDiplomacyPacts_idempotency_uq` UNIQUE (`idempotencyKey`)
);--> statement-breakpoint
CREATE TABLE `aurionGuildMutationPlans` (
  `confirmationHash` varchar(64) NOT NULL,
  `guildId` varchar(64) NOT NULL,
  `actorUserId` int NOT NULL,
  `operation` enum('grant_capability','claim_territory','release_territory','consolidate_kingdom','set_diplomacy') NOT NULL,
  `requiredCapability` enum('member_manage','diplomacy_manage','territory_manage','bank_deposit','bank_withdraw','building_manage','kingdom_consolidate') NOT NULL,
  `expectedRevision` bigint unsigned NOT NULL,
  `idempotencyKey` varchar(128) NOT NULL,
  `payloadHash` varchar(64) NOT NULL,
  `payloadJson` longtext NOT NULL,
  `resourcesJson` longtext NOT NULL,
  `planJson` longtext NOT NULL,
  `status` enum('planned','consumed','expired') NOT NULL DEFAULT 'planned',
  `expiresAt` timestamp NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT current_timestamp(),
  `consumedAt` timestamp NULL DEFAULT NULL,
  CONSTRAINT `aurionGuildMutationPlans_pk` PRIMARY KEY (`confirmationHash`),
  CONSTRAINT `aurionGuildMutationPlans_idempotency_uq` UNIQUE (`idempotencyKey`),
  INDEX `aurionGuildMutationPlans_actor_status_idx` (`actorUserId`,`status`,`expiresAt`)
);--> statement-breakpoint
CREATE TABLE `aurionGuildGovernanceReceipts` (
  `receiptId` varchar(64) NOT NULL,
  `guildId` varchar(64) NOT NULL,
  `actorUserId` int NOT NULL,
  `operation` enum('grant_capability','claim_territory','release_territory','consolidate_kingdom','set_diplomacy') NOT NULL,
  `expectedRevision` bigint unsigned NOT NULL,
  `resultingRevision` bigint unsigned NOT NULL,
  `idempotencyKey` varchar(128) NOT NULL,
  `confirmationHash` varchar(64) NOT NULL,
  `requestHash` varchar(64) NOT NULL,
  `resultHash` varchar(64) NOT NULL,
  `resultJson` longtext NOT NULL,
  `ruleSetVersion` varchar(96) NOT NULL,
  `contentVersion` varchar(96) NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT current_timestamp(),
  CONSTRAINT `aurionGuildGovernanceReceipts_pk` PRIMARY KEY (`receiptId`),
  CONSTRAINT `aurionGuildGovernanceReceipts_idempotency_uq` UNIQUE (`idempotencyKey`),
  CONSTRAINT `aurionGuildGovernanceReceipts_confirmation_uq` UNIQUE (`confirmationHash`),
  CONSTRAINT `aurionGuildGovernanceReceipts_guild_revision_uq` UNIQUE (`guildId`,`resultingRevision`),
  INDEX `aurionGuildGovernanceReceipts_guild_created_idx` (`guildId`,`createdAt`)
);
