CREATE TABLE `aurionProgressionReceipts` (
  `id` varchar(64) NOT NULL,
  `userId` int NOT NULL,
  `characterId` varchar(128) NOT NULL,
  `actionKind` enum('encounter','weapon_use','skill_use','loot_claim') NOT NULL,
  `weaponTrack` varchar(64) NOT NULL,
  `skillId` varchar(96) NOT NULL,
  `resultReceiptId` varchar(128) NOT NULL,
  `sourceReceiptId` varchar(128) NOT NULL,
  `lootReceiptId` varchar(128),
  `masteryEventId` varchar(128),
  `xpGrantedExact` varchar(128) NOT NULL,
  `levelExact` varchar(128) NOT NULL,
  `ruleSetVersion` varchar(96) NOT NULL,
  `contentVersion` varchar(96) NOT NULL,
  `receiptHash` varchar(64) NOT NULL,
  `idempotencyKey` varchar(128) NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT `aurionProgressionReceipts_id` PRIMARY KEY (`id`),
  UNIQUE KEY `aurionProgressionReceipts_user_character_result_uq` (`userId`,`characterId`,`resultReceiptId`),
  UNIQUE KEY `aurionProgressionReceipts_hash_uq` (`receiptHash`),
  UNIQUE KEY `aurionProgressionReceipts_idempotency_uq` (`idempotencyKey`),
  KEY `aurionProgressionReceipts_user_created_idx` (`userId`,`createdAt`)
);
