CREATE TABLE `glbExternalProvenance` (
  `id` varchar(64) NOT NULL,
  `assetId` varchar(64) NOT NULL,
  `sourceKind` enum('os3a-cc0') NOT NULL,
  `registryRepository` varchar(160) NOT NULL,
  `registryRevision` varchar(40) NOT NULL,
  `modelRepository` varchar(160) NOT NULL,
  `modelRevision` varchar(40) NOT NULL,
  `licensePath` varchar(120) NOT NULL,
  `projectId` varchar(96) NOT NULL,
  `sourceAssetId` varchar(96) NOT NULL,
  `sourcePath` varchar(512) NOT NULL,
  `license` varchar(64) NOT NULL,
  `sourceSha256` varchar(64) NOT NULL,
  `sourceBytes` int NOT NULL,
  `sourceMetadataSha256` varchar(64) NOT NULL,
  `fallbackPlanSha256` varchar(64) NOT NULL,
  `receiptSha256` varchar(64) NOT NULL,
  `createdByUserId` int NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT `glbExternalProvenance_id` PRIMARY KEY(`id`),
  CONSTRAINT `glbExternalProvenance_assetId_unique` UNIQUE(`assetId`),
  CONSTRAINT `glbExternalProvenance_receiptSha256_unique` UNIQUE(`receiptSha256`),
  CONSTRAINT `glbExternalProvenance_source_identity_unique` UNIQUE(`projectId`,`sourceAssetId`,`modelRevision`)
);
