import DashboardLayout from "@/components/DashboardLayout";
import ForumAdminComposer from "@/components/ForumAdminComposer";
import ForumAdminEditor from "@/components/ForumAdminEditor";
import GlbSubmissionReview from "@/components/GlbSubmissionReview";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Archive, BadgeDollarSign, Boxes, CheckCircle2, Crown, ExternalLink, Link2, Save, Search, Shield, Sparkles, Trophy, Upload, Users, XCircle } from "lucide-react";
import { useMemo, useState } from "react";
import { Link } from "wouter";

const MAX_GLB_BYTES = 24 * 1024 * 1024;
type AssetType = "character" | "enemy" | "weapon" | "armor" | "arena";

function Stat({ label, value, icon: Icon }: { label: string; value: string | number; icon: typeof Trophy }) {
  return <Card className="border-cyan-300/10 bg-slate-950/70"><CardContent className="pt-5"><div className="flex items-center justify-between"><div><p className="text-[10px] tracking-[.16em] text-cyan-100/55">{label}</p><p className="mt-2 text-2xl font-semibold text-amber-100">{value}</p></div><Icon className="h-5 w-5 text-cyan-300" /></div></CardContent></Card>;
}

function readFileAsBase64(file: File): Promise<string> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onerror = () => reject(new Error("Die GLB-Datei konnte nicht gelesen werden."));
    reader.onload = () => {
      if (typeof reader.result !== "string" || !reader.result.includes(",")) {
        reject(new Error("Die GLB-Datei besitzt kein lesbares Binärformat."));
        return;
      }
      resolve(reader.result.slice(reader.result.indexOf(",") + 1));
    };
    reader.readAsDataURL(file);
  });
}

function AssetStatus({ status }: { status: "draft" | "approved" | "rejected" | "archived" }) {
  const tones = { draft: "border-amber-300/30 text-amber-100", approved: "border-emerald-300/30 text-emerald-100", rejected: "border-red-300/30 text-red-200", archived: "border-slate-400/30 text-slate-300" };
  return <Badge variant="outline" className={tones[status]}>{status}</Badge>;
}

export default function Operations() {
  const { user } = useAuth();
  const utils = trpc.useUtils();
  const [guildName, setGuildName] = useState("");
  const [guildTag, setGuildTag] = useState("");
  const [classCandidate, setClassCandidate] = useState<"vanguard" | "seer" | "warden">("vanguard");
  const [playerSearch, setPlayerSearch] = useState("");
  const [submittedPlayerSearch, setSubmittedPlayerSearch] = useState("");
  const [glbDisplayName, setGlbDisplayName] = useState("");
  const [glbAssetType, setGlbAssetType] = useState<AssetType>("character");
  const [uploadError, setUploadError] = useState<string | null>(null);
  const [readingAsset, setReadingAsset] = useState(false);
  const [assignmentTargets, setAssignmentTargets] = useState<Record<string, string>>({});
  const [roleChoices, setRoleChoices] = useState<Record<number, "user" | "admin">>({});
  const [placementKey, setPlacementKey] = useState("");
  const [placementKind, setPlacementKind] = useState<"banner" | "offerwall" | "vote_list">("banner");
  const [providerLabel, setProviderLabel] = useState("");
  const [placementActive, setPlacementActive] = useState(false);
  const [consentRequired, setConsentRequired] = useState(true);
  const [configurationJson, setConfigurationJson] = useState('{\n  "surface": "ops-preview"\n}');
  const [seasonKey, setSeasonKey] = useState("");
  const [seasonDisplayName, setSeasonDisplayName] = useState("");
  const [rotationConfirmation, setRotationConfirmation] = useState("");
  const [nextSeasonKey, setNextSeasonKey] = useState("");
  const [nextSeasonDisplayName, setNextSeasonDisplayName] = useState("");
  const [selectedSeasonId, setSelectedSeasonId] = useState("");
  const adminPlayerInput = useMemo(() => ({ limit: 25, ...(submittedPlayerSearch ? { query: submittedPlayerSearch } : {}) }), [submittedPlayerSearch]);

  const profile = trpc.player.me.useQuery();
  const leaderboard = trpc.leaderboard.list.useQuery({ limit: 10 });
  const guildCreate = trpc.guild.create.useMutation({ onSuccess: () => { void utils.player.me.invalidate(); setGuildName(""); setGuildTag(""); } });
  const classChoice = trpc.player.chooseClass.useMutation({ onSuccess: () => { void utils.player.me.invalidate(); } });
  const assets = trpc.admin.assets.list.useQuery(undefined, { enabled: user?.role === "admin" });
  const assignments = trpc.admin.assets.listAssignments.useQuery(undefined, { enabled: user?.role === "admin" });
  const placements = trpc.admin.monetization.list.useQuery(undefined, { enabled: user?.role === "admin" });
  const adminPlayers = trpc.admin.players.list.useQuery(adminPlayerInput, { enabled: user?.role === "admin" });
  const assetUpload = trpc.admin.assets.upload.useMutation({ onSuccess: () => { void utils.admin.assets.list.invalidate(); setGlbDisplayName(""); setUploadError(null); } });
  const assetReview = trpc.admin.assets.setReview.useMutation({ onSuccess: () => { void utils.admin.assets.list.invalidate(); } });
  const assetAssign = trpc.admin.assets.assign.useMutation({ onSuccess: () => { void utils.admin.assets.listAssignments.invalidate(); setAssignmentTargets({}); } });
  const placementUpsert = trpc.admin.monetization.upsert.useMutation({ onSuccess: () => { void utils.admin.monetization.list.invalidate(); setPlacementKey(""); setProviderLabel(""); } });
  const roleUpdate = trpc.admin.players.setRole.useMutation({ onSuccess: () => { void utils.admin.players.list.invalidate(); setRoleChoices({}); } });
  const liveAdminRanking = trpc.admin.rankings.live.useQuery({ limit: 25 }, { enabled: user?.role === "admin" });
  const managedSeasons = trpc.admin.rankings.seasons.useQuery({ limit: 25 }, { enabled: user?.role === "admin" });
  const selectedSeasonSnapshots = trpc.admin.rankings.snapshots.useQuery({ seasonId: selectedSeasonId, limit: 50 }, { enabled: user?.role === "admin" && Boolean(selectedSeasonId) });
  const seasonStart = trpc.admin.rankings.startSeason.useMutation({ onSuccess: () => { void utils.admin.rankings.seasons.invalidate(); setSeasonKey(""); setSeasonDisplayName(""); } });
  const seasonRotation = trpc.admin.rankings.rotateSeason.useMutation({ onSuccess: () => { void utils.admin.rankings.seasons.invalidate(); void utils.admin.rankings.live.invalidate(); setRotationConfirmation(""); setNextSeasonKey(""); setNextSeasonDisplayName(""); } });
  const state = profile.data;
  const activeSeason = managedSeasons.data?.find(season => season.status === "active");

  const handleGlbFile = async (file: File | undefined) => {
    if (!file) return;
    if (!file.name.toLowerCase().endsWith(".glb")) {
      setUploadError("Nur binäre GLB-Dateien (.glb) dürfen aufgenommen werden.");
      return;
    }
    if (file.size > MAX_GLB_BYTES) {
      setUploadError("GLB-Dateien dürfen höchstens 24 MiB groß sein.");
      return;
    }
    if (!glbDisplayName.trim()) {
      setUploadError("Vergib vor dem Upload einen Anzeigenamen.");
      return;
    }
    setReadingAsset(true);
    setUploadError(null);
    try {
      assetUpload.mutate({ displayName: glbDisplayName.trim(), assetType: glbAssetType, contentBase64: await readFileAsBase64(file) });
    } catch (error) {
      setUploadError(error instanceof Error ? error.message : "Die GLB-Datei konnte nicht vorbereitet werden.");
    } finally {
      setReadingAsset(false);
    }
  };

  if (profile.isLoading) return <DashboardLayout><div className="min-h-full bg-[#06131a] p-8 text-sm text-cyan-100/70">Operationsdaten werden serverseitig abgeglichen…</div></DashboardLayout>;
  if (profile.isError || !state) return <DashboardLayout><div className="min-h-full bg-[#06131a] p-8 text-sm text-red-200">Operationsdaten konnten nicht geladen werden. Bitte starte die Sitzung erneut.</div></DashboardLayout>;

  return <DashboardLayout><div className="min-h-full bg-[radial-gradient(circle_at_top_right,rgba(45,226,207,.13),transparent_38%),#06131a] p-2 text-slate-100 sm:p-6">
    <div className="mx-auto max-w-6xl space-y-6">
      <header className="flex flex-col gap-4 border-b border-cyan-200/10 pb-6 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs tracking-[.24em] text-cyan-300">AURION // OPERATIONS</p><h1 className="mt-2 text-3xl font-semibold text-amber-100">Expeditionsverwaltung</h1><p className="mt-2 max-w-2xl text-sm text-slate-300">Spielwerte, Gilden und Assets werden serverseitig geführt. Der Browser zeigt bestätigte Zustände, setzt sie aber nicht verbindlich.</p></div><Button asChild variant="outline" className="border-amber-300/30 bg-transparent text-amber-100 hover:bg-amber-200/10"><Link href="/"><ExternalLink className="mr-2 h-4 w-4" />Zum Spiel</Link></Button></header>

      <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat label="STUFE" value={state.profile.level} icon={Sparkles} /><Stat label="AURION-PUNKTE" value={state.profile.aurionPoints} icon={Trophy} /><Stat label="SIEGE" value={state.profile.victories} icon={Crown} /><Stat label="WAFFENPFAD" value={state.weaponMasteries.length} icon={Shield} /></section>

      <Tabs defaultValue="profile" className="w-full"><TabsList className="h-auto flex-wrap justify-start gap-2 bg-transparent p-0"><TabsTrigger value="profile">Profil & Gilde</TabsTrigger><TabsTrigger value="endgame">Endgame</TabsTrigger><TabsTrigger value="ranking">Ranglisten</TabsTrigger>{user?.role === "admin" && <TabsTrigger value="admin">Admin</TabsTrigger>}</TabsList>
        <TabsContent value="profile" className="mt-5 grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><Card className="border-amber-200/15 bg-slate-950/70"><CardHeader><CardTitle className="text-amber-100">Resonanzprofil</CardTitle><CardDescription>Freischaltungen folgen nur bestätigtem serverseitigem Fortschritt.</CardDescription></CardHeader><CardContent className="space-y-4"><div className="flex flex-wrap gap-2"><Badge variant="outline">Klasse: {state.profile.selectedClass}</Badge><Badge variant="outline">XP: {state.profile.totalXp}</Badge>{state.weaponMasteries.map(mastery => <Badge key={mastery.id} className="bg-cyan-500/10 text-cyan-100 hover:bg-cyan-500/10">{mastery.weaponTrack} · M{mastery.level}</Badge>)}</div><div className="rounded-xl border border-cyan-200/10 bg-cyan-400/[.035] p-4"><p className="text-xs tracking-[.14em] text-cyan-200/60">GILDENSTATUS</p>{state.guild ? <div className="mt-2 flex items-center gap-3"><Users className="h-5 w-5 text-cyan-300" /><div><p className="font-medium">[{state.guild.guild.tag}] {state.guild.guild.name}</p><p className="text-sm text-slate-400">Rolle: {state.guild.membership.role} · Saisonpunkte: {state.guild.guild.seasonPoints}</p></div></div> : <p className="mt-2 text-sm text-slate-300">Noch keinem Sternwartenpakt beigetreten.</p>}</div></CardContent></Card>
          <Card className="border-cyan-200/15 bg-slate-950/70"><CardHeader><CardTitle className="text-amber-100">Sternwartenpakt gründen</CardTitle><CardDescription>Eine aktive Mitgliedschaft pro Spieler. Rollen und Beiträge werden serverseitig geprüft.</CardDescription></CardHeader><CardContent><form className="space-y-4" onSubmit={event => { event.preventDefault(); guildCreate.mutate({ name: guildName, tag: guildTag }); }}><div className="space-y-2"><Label htmlFor="guildName">Gildenname</Label><Input id="guildName" value={guildName} maxLength={48} onChange={event => setGuildName(event.target.value)} placeholder="Pakt der Sternenruinen" disabled={Boolean(state.guild)} /></div><div className="space-y-2"><Label htmlFor="guildTag">Tag</Label><Input id="guildTag" value={guildTag} maxLength={8} onChange={event => setGuildTag(event.target.value.toUpperCase())} placeholder="AURION" disabled={Boolean(state.guild)} /></div>{guildCreate.error && <p className="text-sm text-red-300">{guildCreate.error.message}</p>}<Button type="submit" disabled={!guildName || guildTag.length < 2 || guildCreate.isPending || Boolean(state.guild)} className="w-full bg-cyan-500 text-slate-950 hover:bg-cyan-300">{guildCreate.isPending ? "Pakt wird geprüft…" : "Gilde serverseitig gründen"}</Button></form></CardContent></Card></TabsContent>
        <TabsContent value="endgame" className="mt-5 space-y-5">
          <section className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]">
            <Card className="border-amber-200/15 bg-slate-950/70"><CardHeader><CardTitle className="flex items-center gap-2 text-amber-100"><Boxes className="h-5 w-5" />Reliktinventar</CardTitle><CardDescription>Instanzen, Qualität und Affixe stammen vollständig aus bestätigten serverseitigen Drop-Receipts.</CardDescription></CardHeader><CardContent><div className="grid gap-3 sm:grid-cols-2">{state.inventory.map(item => <div key={item.id} className="rounded-xl border border-cyan-200/10 bg-cyan-400/[.03] p-4"><div className="flex items-center justify-between gap-2"><p className="font-medium text-amber-50">{item.baseItemKey.replaceAll("_", " ")}</p><Badge variant="outline" className={item.quality === "unique" ? "border-amber-300/60 text-amber-100" : item.quality === "set" ? "border-emerald-300/50 text-emerald-100" : "border-cyan-300/30 text-cyan-100"}>{item.quality}</Badge></div><p className="mt-1 text-xs text-slate-400">Gegenstandsstufe {item.itemLevel}{item.setKey ? ` · Set: ${item.setKey}` : ""}</p><div className="mt-3 flex flex-wrap gap-1">{item.affixes.map(affix => <Badge key={`${item.id}-${affix.key}`} className="bg-cyan-500/10 text-cyan-100 hover:bg-cyan-500/10">{affix.slot}: {affix.key} · {Object.entries(affix.stats).map(([key, value]) => `${key} +${value}`).join(", ")}</Badge>)}{!item.affixes.length && <span className="text-xs text-slate-500">Keine Affixe</span>}</div></div>)}{!state.inventory.length && <p className="col-span-full py-8 text-sm text-slate-400">Noch keine serverbestätigten Reliktinstanzen. Beute erscheint erst nach validierten Expeditionsergebnissen.</p>}</div></CardContent></Card>
            <div className="space-y-5"><Card className="border-amber-200/15 bg-slate-950/70"><CardHeader><CardTitle className="text-amber-100">Set-Fortschritt</CardTitle><CardDescription>Aktive Boni werden aus deinen gespeicherten Set-Instanzen berechnet.</CardDescription></CardHeader><CardContent className="space-y-3">{state.setBonuses.map(bonus => <div key={`${bonus.setKey}-${bonus.piecesOwned}`} className="rounded-lg border border-emerald-300/15 p-3"><p className="font-medium text-emerald-100">{bonus.displayName}</p><p className="mt-1 text-xs text-slate-400">{bonus.piecesOwned}/{bonus.piecesTotal} Teile</p><div className="mt-2 flex flex-wrap gap-1">{Object.entries(bonus.modifiers).map(([key, value]) => <Badge key={key} variant="outline" className="border-emerald-300/30 text-emerald-100">{key} +{value}</Badge>)}</div></div>)}{!state.setBonuses.length && <p className="text-sm text-slate-400">Noch kein Setbonus aktiv.</p>}</CardContent></Card>
              <Card className="border-cyan-200/15 bg-slate-950/70"><CardHeader><CardTitle className="text-amber-100">Klassenresonanz</CardTitle><CardDescription>Die Spezialisierung wird nur einmal ab Stufe 36 serverseitig akzeptiert; sie legt erlaubte Waffenpfade fest.</CardDescription></CardHeader><CardContent className="space-y-3">{state.profile.selectedClass === "unbound" && state.profile.level >= 36 ? <><select value={classCandidate} onChange={event => setClassCandidate(event.target.value as "vanguard" | "seer" | "warden")} className="flex h-10 w-full rounded-md border border-cyan-200/20 bg-slate-950 px-3 text-sm"><option value="vanguard">Vanguard · blade, spear</option><option value="seer">Seer · staff, focus</option><option value="warden">Warden · spear, focus</option></select>{classChoice.error && <p className="text-sm text-red-300">{classChoice.error.message}</p>}<Button onClick={() => classChoice.mutate({ playerClass: classCandidate })} disabled={classChoice.isPending} className="w-full bg-cyan-500 text-slate-950 hover:bg-cyan-300">{classChoice.isPending ? "Resonanz wird bestätigt…" : "Klasse serverseitig wählen"}</Button></> : <><Badge variant="outline">Aktuelle Klasse: {state.profile.selectedClass}</Badge><p className="text-sm text-slate-400">{state.profile.selectedClass === "unbound" ? `Freischaltung ab Stufe 36 · aktuell Stufe ${state.profile.level}` : "Klassenwahl ist dauerhaft gesichert."}</p></>}</CardContent></Card></div>
          </section>
          <section className="grid gap-5 md:grid-cols-2"><Card className="border-cyan-200/15 bg-slate-950/70"><CardHeader><CardTitle className="text-amber-100">Waffenmeisterschaft</CardTitle><CardDescription>XP wird ausschließlich nach validierten Expeditionsevents gutgeschrieben.</CardDescription></CardHeader><CardContent className="space-y-2">{state.weaponMasteries.map(mastery => <div key={mastery.id} className="flex items-center justify-between rounded-lg border border-cyan-200/10 p-3"><span className="font-medium">{mastery.weaponTrack}</span><span className="text-sm text-cyan-100">Meisterschaft {mastery.level} · {mastery.xp} XP</span></div>)}{!state.weaponMasteries.length && <p className="text-sm text-slate-400">Noch kein bestätigter Waffenpfad.</p>}</CardContent></Card><Card className="border-cyan-200/15 bg-slate-950/70"><CardHeader><CardTitle className="text-amber-100">Langzeitmotiv</CardTitle><CardDescription>Gildenfortschritt, Set-Resonanz und Waffenmeisterschaft verbinden einzelne Expeditionen mit saisonalen Zielen.</CardDescription></CardHeader><CardContent className="space-y-2 text-sm text-slate-300">{state.guild ? <><p className="font-medium text-cyan-100">[{state.guild.guild.tag}] {state.guild.guild.name}</p><p>Gildenstufe {state.guild.guild.level} · Saisonpunkte {state.guild.guild.seasonPoints}</p><p className="text-xs text-slate-400">Rolle: {state.guild.membership.role}. Beiträge bleiben nur mit serverseitigen Receipts gültig.</p></> : <p>Gründe oder finde einen Sternwartenpakt, um gemeinsame saisonale Ziele freizuschalten.</p>}</CardContent></Card></section>
        </TabsContent>
        <TabsContent value="ranking" className="mt-5"><Card className="border-cyan-200/15 bg-slate-950/70"><CardHeader><CardTitle className="text-amber-100">Saison-Rangliste</CardTitle><CardDescription>Sortiert nach bestätigten Saisonpunkten, Siegen und Stufe.</CardDescription></CardHeader><CardContent><div className="divide-y divide-cyan-200/10">{leaderboard.data?.map((entry, index) => <div key={entry.userId} className="flex items-center gap-4 py-3"><span className="w-7 text-center text-sm text-cyan-200">{index + 1}</span><div className="min-w-0 flex-1"><p className="truncate font-medium">{entry.name || `Explorer ${entry.userId}`}</p><p className="text-xs text-slate-400">{entry.selectedClass} · Stufe {entry.level}</p></div><div className="text-right text-sm"><p className="text-amber-100">{entry.seasonPoints} SP</p><p className="text-slate-400">{entry.victories} Siege</p></div></div>)}{!leaderboard.data?.length && <p className="py-8 text-sm text-slate-400">Noch keine bestätigten Expeditionswerte.</p>}</div></CardContent></Card></TabsContent>
        {user?.role === "admin" && <TabsContent value="admin" className="mt-5 space-y-5">
          <ForumAdminComposer />
          <ForumAdminEditor />
          <GlbSubmissionReview />
          <section className="grid gap-5 xl:grid-cols-[1.35fr_.65fr]"><Card className="border-amber-200/15 bg-slate-950/70"><CardHeader><CardTitle className="flex items-center gap-2 text-amber-100"><Users className="h-5 w-5" />Spielerverzeichnis</CardTitle><CardDescription>Serverseitig aggregierte Profile; die Suche akzeptiert nur begrenzte Namens- und E-Mail-Fragmente.</CardDescription></CardHeader><CardContent className="space-y-4"><form className="flex gap-2" onSubmit={event => { event.preventDefault(); setSubmittedPlayerSearch(playerSearch.trim()); }}><Input value={playerSearch} maxLength={64} onChange={event => setPlayerSearch(event.target.value)} placeholder="Name oder E-Mail suchen" /><Button type="submit" variant="outline" className="border-cyan-300/30"><Search className="h-4 w-4" /><span className="sr-only">Suchen</span></Button></form><div className="max-h-80 divide-y divide-cyan-200/10 overflow-auto">{adminPlayers.data?.map(player => <div key={player.userId} className="flex items-center gap-3 py-3 text-sm"><div className="min-w-0 flex-1"><p className="truncate font-medium text-amber-50">{player.name || `Explorer ${player.userId}`}</p><p className="truncate text-xs text-slate-400">{player.email || "Keine E-Mail"} · {player.role}</p></div><div className="text-right text-xs text-cyan-100/80"><p>Stufe {player.level ?? 1} · {player.victories ?? 0} Siege</p><p>{player.guildTag ? `[${player.guildTag}] ${player.guildName}` : "ohne Gilde"}</p></div></div>)}{!adminPlayers.data?.length && <p className="py-8 text-sm text-slate-400">Keine passenden serverseitig gespeicherten Spielerprofile.</p>}</div></CardContent></Card>
            <Card className="border-amber-200/15 bg-slate-950/70"><CardHeader><CardTitle className="flex items-center gap-2 text-amber-100"><BadgeDollarSign className="h-5 w-5" />Platzierungsprinzip</CardTitle><CardDescription>Konfiguration speichert nur sichtbare Placementdaten, niemals Provider-Schlüssel oder Tokens.</CardDescription></CardHeader><CardContent className="space-y-3 text-sm text-slate-300"><p>Aktivierungen sind explizit und Einwilligung bleibt je Fläche verbindlich.</p><p>Reward- und Provider-Callbacks benötigen weiterhin eine getrennte serverseitige Verifikation.</p><Badge variant="outline" className="border-cyan-300/30 text-cyan-100">kein Secret im Browser</Badge></CardContent></Card></section>

          <section className="grid gap-5 xl:grid-cols-2"><Card className="border-amber-200/15 bg-slate-950/70"><CardHeader><CardTitle className="flex items-center gap-2 text-amber-100"><Upload className="h-5 w-5" />GLB aufnehmen</CardTitle><CardDescription>Maximal 24 MiB; der Server prüft GLB-v2-Kopf, Länge und SHA-256, schreibt die Bytes nach S3 und legt die Metadaten als Entwurf an.</CardDescription></CardHeader><CardContent><div className="space-y-4"><div className="space-y-2"><Label htmlFor="glbName">Anzeigename</Label><Input id="glbName" value={glbDisplayName} maxLength={120} onChange={event => setGlbDisplayName(event.target.value)} placeholder="Explorer Mk II" /></div><div className="space-y-2"><Label htmlFor="glbType">Asset-Typ</Label><select id="glbType" value={glbAssetType} onChange={event => setGlbAssetType(event.target.value as AssetType)} className="flex h-10 w-full rounded-md border border-cyan-200/20 bg-slate-950 px-3 text-sm"><option value="character">Character</option><option value="enemy">Enemy</option><option value="weapon">Weapon</option><option value="armor">Armor</option><option value="arena">Arena</option></select></div><div className="space-y-2"><Label htmlFor="glbUpload">Binäres GLB</Label><Input id="glbUpload" type="file" accept=".glb,model/gltf-binary" disabled={readingAsset || assetUpload.isPending} onChange={event => { void handleGlbFile(event.target.files?.[0]); event.currentTarget.value = ""; }} /></div>{(uploadError || assetUpload.error) && <p className="text-sm text-red-300">{uploadError || assetUpload.error?.message}</p>}<p className="text-xs text-cyan-100/55">{readingAsset ? "Binärdatei wird lokal vorbereitet…" : assetUpload.isPending ? "S3-Aufnahme und Metadaten-Readback laufen…" : "Nach Aufnahme muss ein Admin das Asset freigeben."}</p></div></CardContent></Card>
            <Card className="border-amber-200/15 bg-slate-950/70"><CardHeader><CardTitle className="flex items-center gap-2 text-amber-100"><Save className="h-5 w-5" />Platzierung speichern</CardTitle><CardDescription>Die JSON-Konfiguration wird als öffentliche, nicht geheime Platzierungsbeschreibung validiert.</CardDescription></CardHeader><CardContent><form className="space-y-3" onSubmit={event => { event.preventDefault(); placementUpsert.mutate({ placementKey, kind: placementKind, providerLabel, active: placementActive, consentRequired, configurationJson }); }}><div className="grid gap-3 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor="placementKey">Placement-Key</Label><Input id="placementKey" value={placementKey} onChange={event => setPlacementKey(event.target.value.toLowerCase())} placeholder="mission_banner" /></div><div className="space-y-2"><Label htmlFor="providerLabel">Provider-Label</Label><Input id="providerLabel" value={providerLabel} onChange={event => setProviderLabel(event.target.value)} placeholder="Verifizierter Provider" /></div></div><div className="space-y-2"><Label htmlFor="placementKind">Typ</Label><select id="placementKind" value={placementKind} onChange={event => setPlacementKind(event.target.value as "banner" | "offerwall" | "vote_list")} className="flex h-10 w-full rounded-md border border-cyan-200/20 bg-slate-950 px-3 text-sm"><option value="banner">Banner</option><option value="offerwall">Offerwall</option><option value="vote_list">Vote-Liste</option></select></div><div className="space-y-2"><Label htmlFor="placementConfig">Öffentliche JSON-Konfiguration</Label><textarea id="placementConfig" value={configurationJson} onChange={event => setConfigurationJson(event.target.value)} rows={4} className="flex w-full rounded-md border border-cyan-200/20 bg-slate-950 px-3 py-2 font-mono text-xs" /></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={placementActive} onChange={event => setPlacementActive(event.target.checked)} /> Aktiv</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={consentRequired} onChange={event => setConsentRequired(event.target.checked)} /> Einwilligung erforderlich</label>{placementUpsert.error && <p className="text-sm text-red-300">{placementUpsert.error.message}</p>}<Button type="submit" disabled={!placementKey || !providerLabel || placementUpsert.isPending} className="w-full bg-cyan-500 text-slate-950 hover:bg-cyan-300">{placementUpsert.isPending ? "Server prüft…" : "Platzierung speichern"}</Button></form></CardContent></Card></section>

          <section className="grid gap-5 xl:grid-cols-2"><Card className="border-amber-200/15 bg-slate-950/70"><CardHeader><CardTitle className="flex items-center gap-2 text-amber-100"><Boxes className="h-5 w-5" />GLB-Katalog & Review</CardTitle><CardDescription>Nur freigegebene Assets dürfen einer Spielfigur, einem Gegner, einer Waffe, Rüstung oder Arena aktiv zugewiesen werden.</CardDescription></CardHeader><CardContent className="space-y-3">{assets.data?.map(asset => <div key={asset.id} className="rounded-lg border border-cyan-200/10 p-3 text-sm"><div className="flex flex-wrap items-center gap-2"><b className="mr-auto">{asset.displayName}</b><AssetStatus status={asset.status} /><Badge variant="outline">{asset.assetType}</Badge></div><p className="mt-1 text-xs text-slate-400">{asset.bytes.toLocaleString()} Bytes · {asset.sha256.slice(0, 12)}…</p><div className="mt-3 flex flex-wrap gap-2"><Button size="sm" variant="outline" className="border-emerald-300/30 text-emerald-100" disabled={assetReview.isPending} onClick={() => assetReview.mutate({ assetId: asset.id, status: "approved" })}><CheckCircle2 className="mr-1 h-3.5 w-3.5" />Freigeben</Button><Button size="sm" variant="outline" className="border-red-300/30 text-red-200" disabled={assetReview.isPending} onClick={() => assetReview.mutate({ assetId: asset.id, status: "rejected" })}><XCircle className="mr-1 h-3.5 w-3.5" />Ablehnen</Button><Button size="sm" variant="outline" className="border-slate-400/30 text-slate-300" disabled={assetReview.isPending} onClick={() => assetReview.mutate({ assetId: asset.id, status: "archived" })}><Archive className="mr-1 h-3.5 w-3.5" />Archivieren</Button></div>{asset.status === "approved" && <div className="mt-3 flex gap-2"><Input value={assignmentTargets[asset.id] ?? ""} maxLength={120} onChange={event => setAssignmentTargets(current => ({ ...current, [asset.id]: event.target.value }))} placeholder="Zielschlüssel, z. B. explorer" /><Button size="sm" disabled={!assignmentTargets[asset.id] || assetAssign.isPending} onClick={() => assetAssign.mutate({ assetId: asset.id, targetType: asset.assetType, targetKey: assignmentTargets[asset.id]!, expectedActiveAssetId: assignments.data?.find(entry => entry.targetType === asset.assetType && entry.targetKey === assignmentTargets[asset.id] && entry.active === 1)?.assetId ?? null })}><Link2 className="mr-1 h-3.5 w-3.5" />Zuweisen</Button></div>}</div>)}{!assets.data?.length && <p className="text-sm text-slate-400">Noch keine GLB-Metadaten eingetragen.</p>}{(assetReview.error || assetAssign.error) && <p className="text-sm text-red-300">{assetReview.error?.message || assetAssign.error?.message}</p>}</CardContent></Card>
            <Card className="border-amber-200/15 bg-slate-950/70"><CardHeader><CardTitle className="text-amber-100">Aktive Zuweisungen & Flächen</CardTitle><CardDescription>Die zuletzt bestätigte aktive Zuweisung überschreibt serverseitig eine vorherige Zuweisung auf dasselbe Ziel.</CardDescription></CardHeader><CardContent className="space-y-5"><div className="space-y-2">{assignments.data?.map(assignment => <div key={assignment.id} className="rounded-lg border border-cyan-200/10 p-3 text-sm"><p className="font-medium">{assignment.targetType}:{assignment.targetKey}</p><p className="text-xs text-slate-400">{assignment.displayName} · {assignment.active ? "aktiv" : "historisch"}</p></div>)}{!assignments.data?.length && <p className="text-sm text-slate-400">Noch keine bestätigten Zielzuweisungen.</p>}</div><div className="border-t border-cyan-200/10 pt-4 space-y-2">{placements.data?.map(placement => <div key={placement.id} className="rounded-lg border border-cyan-200/10 p-3 text-sm"><div className="flex items-center justify-between gap-2"><b>{placement.placementKey}</b><Badge variant="outline">{placement.kind}</Badge></div><p className="mt-1 text-xs text-slate-400">{placement.active ? "Aktiv" : "Deaktiviert"} · Einwilligung: {placement.consentRequired ? "erforderlich" : "nicht erforderlich"}</p></div>)}{!placements.data?.length && <p className="text-sm text-slate-400">Keine gespeicherten Werbe-, Offerwall- oder Vote-Konfigurationen.</p>}</div></CardContent></Card></section>

          <section className="grid gap-5 xl:grid-cols-2">
            <Card className="border-amber-200/15 bg-slate-950/70">
              <CardHeader><CardTitle className="flex items-center gap-2 text-amber-100"><Shield className="h-5 w-5" />Rollenverwaltung</CardTitle><CardDescription>Die eigene Rolle und die Rolle des Projekteigentümers sind serverseitig gegen Änderungen über diese Konsole geschützt.</CardDescription></CardHeader>
              <CardContent className="space-y-3"><div className="max-h-96 divide-y divide-cyan-200/10 overflow-auto">{adminPlayers.data?.map(player => {
                const selectedRole = roleChoices[player.userId] ?? player.role;
                const isSelf = player.userId === user.id;
                return <div key={`role-${player.userId}`} className="flex flex-wrap items-center gap-2 py-3 text-sm"><div className="min-w-0 flex-1"><p className="truncate font-medium">{player.name || `Explorer ${player.userId}`}</p><p className="text-xs text-slate-400">{player.email || "Keine E-Mail"}</p></div><select value={selectedRole} disabled={isSelf || roleUpdate.isPending} onChange={event => setRoleChoices(current => ({ ...current, [player.userId]: event.target.value as "user" | "admin" }))} className="h-9 rounded-md border border-cyan-200/20 bg-slate-950 px-2 text-xs"><option value="user">user</option><option value="admin">admin</option></select><Button size="sm" variant="outline" className="border-cyan-300/30" disabled={isSelf || selectedRole === player.role || roleUpdate.isPending} onClick={() => roleUpdate.mutate({ userId: player.userId, role: selectedRole })}>Bestätigen</Button></div>;
              })}{!adminPlayers.data?.length && <p className="py-8 text-sm text-slate-400">Keine verwaltbaren Profile in der aktuellen Suche.</p>}</div>{roleUpdate.error && <p className="text-sm text-red-300">{roleUpdate.error.message}</p>}</CardContent>
            </Card>
            <Card className="border-amber-200/15 bg-slate-950/70">
              <CardHeader><CardTitle className="flex items-center gap-2 text-amber-100"><Trophy className="h-5 w-5" />Live-Rangliste</CardTitle><CardDescription>Administrative Einsicht zeigt die aktuellen bestätigten Saisonpunkte; die öffentliche Rangliste bleibt davon getrennt.</CardDescription></CardHeader>
              <CardContent className="divide-y divide-cyan-200/10">{liveAdminRanking.data?.map((entry, index) => <div key={entry.userId} className="flex items-center gap-3 py-3 text-sm"><span className="w-6 text-cyan-200">{index + 1}</span><div className="min-w-0 flex-1"><p className="truncate font-medium">{entry.name || `Explorer ${entry.userId}`}</p><p className="text-xs text-slate-400">{entry.email || "keine E-Mail"} · {entry.selectedClass}</p></div><p className="text-right text-xs text-amber-100">{entry.seasonPoints} SP<br /><span className="text-slate-400">{entry.victories} Siege · L{entry.level}</span></p></div>)}{!liveAdminRanking.data?.length && <p className="py-8 text-sm text-slate-400">Noch keine bestätigten Saisonwerte.</p>}</CardContent>
            </Card>
          </section>

          <section className="grid gap-5 xl:grid-cols-2">
            <Card className="border-amber-200/15 bg-slate-950/70">
              <CardHeader><CardTitle className="flex items-center gap-2 text-amber-100"><Sparkles className="h-5 w-5" />Saison starten</CardTitle><CardDescription>Start ist nur ohne aktive Saison möglich und verwendet einen Idempotenzschlüssel gegen doppelte Ausführung.</CardDescription></CardHeader>
              <CardContent><form className="space-y-3" onSubmit={event => { event.preventDefault(); seasonStart.mutate({ seasonKey, displayName: seasonDisplayName, idempotencyKey: `season-start:${seasonKey}` }); }}><div className="space-y-2"><Label htmlFor="seasonKey">Saison-Key</Label><Input id="seasonKey" value={seasonKey} onChange={event => setSeasonKey(event.target.value.toLowerCase())} placeholder="aurion_s01" disabled={Boolean(activeSeason)} /></div><div className="space-y-2"><Label htmlFor="seasonName">Anzeigename</Label><Input id="seasonName" value={seasonDisplayName} onChange={event => setSeasonDisplayName(event.target.value)} placeholder="Sternwarte: Erwachen" disabled={Boolean(activeSeason)} /></div>{activeSeason && <p className="text-xs text-amber-100">Aktive Saison: {activeSeason.displayName} ({activeSeason.seasonKey})</p>}{seasonStart.error && <p className="text-sm text-red-300">{seasonStart.error.message}</p>}<Button type="submit" disabled={Boolean(activeSeason) || !seasonKey || !seasonDisplayName || seasonStart.isPending} className="w-full bg-cyan-500 text-slate-950 hover:bg-cyan-300">{seasonStart.isPending ? "Saison wird bestätigt…" : "Saison serverseitig starten"}</Button></form></CardContent>
            </Card>
            <Card className="border-red-300/20 bg-slate-950/70">
              <CardHeader><CardTitle className="flex items-center gap-2 text-amber-100"><Archive className="h-5 w-5" />Saison rotieren</CardTitle><CardDescription>Der bestätigte aktive Key wird mit dem Server verglichen. Erst dann werden Standings archiviert und aktuelle Saisonpunkte zurückgesetzt.</CardDescription></CardHeader>
              <CardContent><form className="space-y-3" onSubmit={event => { event.preventDefault(); if (!activeSeason) return; seasonRotation.mutate({ confirmedSeasonKey: rotationConfirmation, nextSeasonKey, nextDisplayName: nextSeasonDisplayName, idempotencyKey: `season-rotate:${activeSeason.seasonKey}:${nextSeasonKey}` }); }}><div className="space-y-2"><Label htmlFor="rotationConfirm">Aktiven Key zur Bestätigung eingeben</Label><Input id="rotationConfirm" value={rotationConfirmation} onChange={event => setRotationConfirmation(event.target.value.toLowerCase())} placeholder={activeSeason?.seasonKey || "keine aktive Saison"} disabled={!activeSeason} /></div><div className="grid gap-3 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor="nextSeasonKey">Nächster Key</Label><Input id="nextSeasonKey" value={nextSeasonKey} onChange={event => setNextSeasonKey(event.target.value.toLowerCase())} placeholder="aurion_s02" disabled={!activeSeason} /></div><div className="space-y-2"><Label htmlFor="nextSeasonName">Nächster Name</Label><Input id="nextSeasonName" value={nextSeasonDisplayName} onChange={event => setNextSeasonDisplayName(event.target.value)} placeholder="Sternwarte: Nachhall" disabled={!activeSeason} /></div></div>{seasonRotation.error && <p className="text-sm text-red-300">{seasonRotation.error.message}</p>}<Button type="submit" variant="outline" disabled={!activeSeason || rotationConfirmation !== activeSeason.seasonKey || !nextSeasonKey || !nextSeasonDisplayName || seasonRotation.isPending} className="w-full border-red-300/40 text-red-100 hover:bg-red-400/10">{seasonRotation.isPending ? "Archivierung läuft…" : "Archivieren und neue Saison starten"}</Button></form></CardContent>
            </Card>
          </section>

          <section className="grid gap-5 xl:grid-cols-2"><Card className="border-amber-200/15 bg-slate-950/70"><CardHeader><CardTitle className="text-amber-100">Saisonarchiv</CardTitle><CardDescription>Geschlossene Saisons enthalten serverseitig aufgenommene Ranglistensnapshots.</CardDescription></CardHeader><CardContent className="space-y-2">{managedSeasons.data?.map(season => <button type="button" key={season.id} onClick={() => setSelectedSeasonId(season.id)} className={`w-full rounded-lg border p-3 text-left text-sm transition-colors ${selectedSeasonId === season.id ? "border-cyan-300/60 bg-cyan-400/10" : "border-cyan-200/10 hover:bg-cyan-400/[.04]"}`}><span className="font-medium">{season.displayName}</span><span className="ml-2 text-xs text-cyan-100/60">{season.status}</span><p className="mt-1 text-xs text-slate-400">{season.seasonKey} · Start {new Date(season.startsAt).toLocaleDateString()}</p></button>)}{!managedSeasons.data?.length && <p className="py-8 text-sm text-slate-400">Noch keine Saison wurde serverseitig gestartet.</p>}</CardContent></Card><Card className="border-amber-200/15 bg-slate-950/70"><CardHeader><CardTitle className="text-amber-100">Archivierte Standings</CardTitle><CardDescription>{selectedSeasonId ? "Sortiert nach gesicherten Saisonpunkten, Siegen und Stufe." : "Wähle links eine geschlossene Saison aus."}</CardDescription></CardHeader><CardContent className="divide-y divide-cyan-200/10">{selectedSeasonSnapshots.data?.map((entry, index) => <div key={entry.userId} className="flex items-center gap-3 py-3 text-sm"><span className="w-6 text-cyan-200">{index + 1}</span><div className="min-w-0 flex-1"><p className="truncate font-medium">{entry.name || `Explorer ${entry.userId}`}</p><p className="text-xs text-slate-400">{entry.selectedClass} · L{entry.level}</p></div><p className="text-right text-xs text-amber-100">{entry.seasonPoints} SP<br /><span className="text-slate-400">{entry.victories} Siege</span></p></div>)}{selectedSeasonId && !selectedSeasonSnapshots.data?.length && <p className="py-8 text-sm text-slate-400">Für diese Saison wurden keine Standings archiviert.</p>}</CardContent></Card></section>
        </TabsContent>}
      </Tabs>
    </div>
  </div></DashboardLayout>;
}
