import DashboardLayout from "@/components/DashboardLayout";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Boxes, Crown, ExternalLink, Shield, Sparkles, Trophy, Users } from "lucide-react";
import { useState } from "react";
import { Link } from "wouter";

function Stat({ label, value, icon: Icon }: { label: string; value: string | number; icon: typeof Trophy }) {
  return <Card className="bg-slate-950/70 border-cyan-300/10"><CardContent className="pt-5"><div className="flex items-center justify-between"><div><p className="text-[10px] tracking-[.16em] text-cyan-100/55">{label}</p><p className="mt-2 text-2xl font-semibold text-amber-100">{value}</p></div><Icon className="h-5 w-5 text-cyan-300" /></div></CardContent></Card>;
}

export default function Operations() {
  const { user } = useAuth();
  const utils = trpc.useUtils();
  const [guildName, setGuildName] = useState("");
  const [guildTag, setGuildTag] = useState("");
  const profile = trpc.player.me.useQuery();
  const leaderboard = trpc.leaderboard.list.useQuery({ limit: 10 });
  const guildCreate = trpc.guild.create.useMutation({ onSuccess: () => { void utils.player.me.invalidate(); setGuildName(""); setGuildTag(""); } });
  const assets = trpc.admin.assets.list.useQuery(undefined, { enabled: user?.role === "admin" });
  const placements = trpc.admin.monetization.list.useQuery(undefined, { enabled: user?.role === "admin" });
  const state = profile.data;

  if (profile.isLoading) return <DashboardLayout><div className="min-h-full bg-[#06131a] p-8 text-sm text-cyan-100/70">Operationsdaten werden serverseitig abgeglichen…</div></DashboardLayout>;
  if (profile.isError || !state) return <DashboardLayout><div className="min-h-full bg-[#06131a] p-8 text-sm text-red-200">Operationsdaten konnten nicht geladen werden. Bitte starte die Sitzung erneut.</div></DashboardLayout>;

  return <DashboardLayout><div className="min-h-full bg-[radial-gradient(circle_at_top_right,rgba(45,226,207,.13),transparent_38%),#06131a] text-slate-100 p-2 sm:p-6">
    <div className="mx-auto max-w-6xl space-y-6">
      <header className="flex flex-col gap-4 border-b border-cyan-200/10 pb-6 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs tracking-[.24em] text-cyan-300">AURION // OPERATIONS</p><h1 className="mt-2 text-3xl font-semibold text-amber-100">Expeditionsverwaltung</h1><p className="mt-2 max-w-2xl text-sm text-slate-300">Spielwerte, Gilden und Assets werden serverseitig geführt. Der Browser zeigt bestätigte Zustände, setzt sie aber nicht verbindlich.</p></div><Button asChild variant="outline" className="border-amber-300/30 bg-transparent text-amber-100 hover:bg-amber-200/10"><Link href="/"><ExternalLink className="mr-2 h-4 w-4" /> Zum Spiel</Link></Button></header>

      <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat label="STUFE" value={state?.profile.level ?? "–"} icon={Sparkles} /><Stat label="AURION-PUNKTE" value={state?.profile.aurionPoints ?? "–"} icon={Trophy} /><Stat label="SIEGE" value={state?.profile.victories ?? "–"} icon={Crown} /><Stat label="WAFFENPFAD" value={state?.weaponMasteries.length ?? "–"} icon={Shield} /></section>

      <Tabs defaultValue="profile" className="w-full"><TabsList className="h-auto flex-wrap justify-start gap-2 bg-transparent p-0"><TabsTrigger value="profile">Profil & Gilde</TabsTrigger><TabsTrigger value="ranking">Ranglisten</TabsTrigger>{user?.role === "admin" && <TabsTrigger value="admin">Admin</TabsTrigger>}</TabsList>
        <TabsContent value="profile" className="mt-5 grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><Card className="border-amber-200/15 bg-slate-950/70"><CardHeader><CardTitle className="text-amber-100">Resonanzprofil</CardTitle><CardDescription>Freischaltungen folgen nur bestätigtem serverseitigem Fortschritt.</CardDescription></CardHeader><CardContent className="space-y-4"><div className="flex flex-wrap gap-2"><Badge variant="outline">Klasse: {state?.profile.selectedClass ?? "unbound"}</Badge><Badge variant="outline">XP: {state?.profile.totalXp ?? 0}</Badge>{state?.weaponMasteries.map(mastery => <Badge key={mastery.id} className="bg-cyan-500/10 text-cyan-100 hover:bg-cyan-500/10">{mastery.weaponTrack} · M{mastery.level}</Badge>)}</div><div className="rounded-xl border border-cyan-200/10 bg-cyan-400/[.035] p-4"><p className="text-xs tracking-[.14em] text-cyan-200/60">GILDENSTATUS</p>{state?.guild ? <div className="mt-2 flex items-center gap-3"><Users className="h-5 w-5 text-cyan-300" /><div><p className="font-medium">[{state.guild.guild.tag}] {state.guild.guild.name}</p><p className="text-sm text-slate-400">Rolle: {state.guild.membership.role} · Saisonpunkte: {state.guild.guild.seasonPoints}</p></div></div> : <p className="mt-2 text-sm text-slate-300">Noch keinem Sternwartenpakt beigetreten.</p>}</div></CardContent></Card>
          <Card className="border-cyan-200/15 bg-slate-950/70"><CardHeader><CardTitle className="text-amber-100">Sternwartenpakt gründen</CardTitle><CardDescription>Eine aktive Mitgliedschaft pro Spieler. Rollen und Beiträge werden serverseitig geprüft.</CardDescription></CardHeader><CardContent><form className="space-y-4" onSubmit={event => { event.preventDefault(); guildCreate.mutate({ name: guildName, tag: guildTag }); }}><div className="space-y-2"><Label htmlFor="guildName">Gildenname</Label><Input id="guildName" value={guildName} maxLength={48} onChange={event => setGuildName(event.target.value)} placeholder="Pakt der Sternenruinen" disabled={Boolean(state?.guild)} /></div><div className="space-y-2"><Label htmlFor="guildTag">Tag</Label><Input id="guildTag" value={guildTag} maxLength={8} onChange={event => setGuildTag(event.target.value.toUpperCase())} placeholder="AURION" disabled={Boolean(state?.guild)} /></div>{guildCreate.error && <p className="text-sm text-red-300">{guildCreate.error.message}</p>}<Button type="submit" disabled={!guildName || guildTag.length < 2 || guildCreate.isPending || Boolean(state?.guild)} className="w-full bg-cyan-500 text-slate-950 hover:bg-cyan-300">{guildCreate.isPending ? "Pakt wird geprüft…" : "Gilde serverseitig gründen"}</Button></form></CardContent></Card></TabsContent>
        <TabsContent value="ranking" className="mt-5"><Card className="border-cyan-200/15 bg-slate-950/70"><CardHeader><CardTitle className="text-amber-100">Saison-Rangliste</CardTitle><CardDescription>Sortiert nach bestätigten Saisonpunkten, Siegen und Stufe.</CardDescription></CardHeader><CardContent><div className="divide-y divide-cyan-200/10">{leaderboard.data?.map((entry, index) => <div key={entry.userId} className="flex items-center gap-4 py-3"><span className="w-7 text-center text-sm text-cyan-200">{index + 1}</span><div className="min-w-0 flex-1"><p className="truncate font-medium">{entry.name || `Explorer ${entry.userId}`}</p><p className="text-xs text-slate-400">{entry.selectedClass} · Stufe {entry.level}</p></div><div className="text-right text-sm"><p className="text-amber-100">{entry.seasonPoints} SP</p><p className="text-slate-400">{entry.victories} Siege</p></div></div>)}{!leaderboard.data?.length && <p className="py-8 text-sm text-slate-400">Noch keine bestätigten Expeditionswerte.</p>}</div></CardContent></Card></TabsContent>
        {user?.role === "admin" && <TabsContent value="admin" className="mt-5 grid gap-5 lg:grid-cols-2"><Card className="border-amber-200/15 bg-slate-950/70"><CardHeader><CardTitle className="flex items-center gap-2 text-amber-100"><Boxes className="h-5 w-5" /> GLB-Katalog</CardTitle><CardDescription>Nur freigegebene S3-Assets dürfen in Spielfelder zugewiesen werden.</CardDescription></CardHeader><CardContent className="space-y-2">{assets.data?.map(asset => <div key={asset.id} className="rounded-lg border border-cyan-200/10 p-3 text-sm"><b>{asset.displayName}</b><span className="ml-2 text-cyan-200">{asset.assetType}</span><p className="mt-1 text-xs text-slate-400">{asset.status} · {asset.bytes.toLocaleString()} Bytes</p></div>)}{!assets.data?.length && <p className="text-sm text-slate-400">Noch keine GLB-Metadaten eingetragen. Der Upload-Flow wird erst nach S3-Prüfung freigegeben.</p>}</CardContent></Card><Card className="border-amber-200/15 bg-slate-950/70"><CardHeader><CardTitle className="text-amber-100">Monetarisierungsflächen</CardTitle><CardDescription>Provider-Geheimnisse werden nie hier angezeigt oder im Browser gespeichert.</CardDescription></CardHeader><CardContent className="space-y-2">{placements.data?.map(placement => <div key={placement.id} className="rounded-lg border border-cyan-200/10 p-3 text-sm"><b>{placement.placementKey}</b><span className="ml-2 text-cyan-200">{placement.kind}</span><p className="mt-1 text-xs text-slate-400">{placement.active ? "Aktiv" : "Deaktiviert"} · Einwilligung: {placement.consentRequired ? "erforderlich" : "nicht erforderlich"}</p></div>)}{!placements.data?.length && <p className="text-sm text-slate-400">Keine aktive Werbe-, Offerwall- oder Vote-Konfiguration.</p>}</CardContent></Card></TabsContent>}
      </Tabs>
    </div>
  </div></DashboardLayout>;
}
