"""Independent integer/rational oracle for the TypeScript protocol sample.

No network, database, fixture substitution or gameplay mutation. Input must be
generated by aim265-v2.ts in the same checkout; source hashes are re-read here.
"""
import hashlib
import json
import math
import sys
from fractions import Fraction
from pathlib import Path


def root5(value):
    # Newton iteration is independent of the production binary-search root.
    if value == 0:
        return 0
    current = 1 << ((value.bit_length() + 4) // 5)
    while True:
        following = (4 * current + value // current**4) // 5
        if following >= current:
            break
        current = following
    while current**5 > value:
        current -= 1
    while (current + 1)**5 <= value:
        current += 1
    return current


def verify(report):
    assert report['rulesetVersion'] == 'aurion-balancing-candidate.v2'
    assert report['final'] is False
    assert report['authority'] == 'analysis_only_no_gameplay_mutation'
    for source in report['source']['files']:
        assert hashlib.sha256(Path(source['path']).read_bytes()).hexdigest() == source['sha256'], source['path']
    content = json.loads(Path('shared/aurionAx1ContentCatalog.json').read_text())
    for area in ['professions', 'activities', 'recipes', 'dungeons', 'worldBosses']:
        assert {x['id'] for x in report[area]} == {x['id'] for x in content[area]}, area
    assert len(report['homesteads']) == 4 and len(report['guildBuildings']) == 6
    pacing = {'weapon': 10000, 'profession': 9000, 'recipe': 7000, 'item': 6500, 'social': 11000, 'politics': 13000, 'navigation': 8500, 'gathering': 8500, 'combat_action': 7500}
    cumulative = [0]
    previous = 0
    for level in range(1, 10001):
        required = root5(50**5 * level**7)
        assert required > previous
        previous = required
        cumulative.append(cumulative[-1] + required)
    for row in report['progression']:
        level, required = int(row['levelExact']), int(row['xpNextExact'])
        exact_power = 50**5 * level**7
        assert required**5 <= exact_power < (required + 1)**5
        assert required == root5(exact_power)
        if row['cumulativeXpExact'] is not None:
            assert int(row['cumulativeXpExact']) == cumulative[level - 1]
        for scope, multiplier in pacing.items():
            assert int(row['targetActions'][scope]) == ((20 + 12 * math.isqrt(level - 1)) * multiplier + 9999) // 10000
        quotient, remainder = divmod(max(0, level - 49), 1000)
        assert int(row['yield']['guaranteedBonusBatchesExact']) == quotient
        assert row['yield']['bonusChanceBps'] == remainder * 10
        modifiers = row['modifiers']
        assert modifiers['efficiencyBps'] == 10000 + 2000 * level // (level + 200)
        assert modifiers['speedBps'] == 10000 + 4000 * level // (level + 250)
        assert modifiers['stabilityBps'] == 7000 + 3000 * level // (level + 100)
        assert modifiers['errorChanceBps'] == 200000 // (level + 100)
        assert 10000 <= modifiers['qualityPowerBps'] <= 13000
    activities = {row['output'][0]: row for row in content['activities']}
    for recipe in report['recipes']:
        minimum = maximum = 0
        for material, quantity in recipe['ingredients']:
            duration, _, low, high = activities[material]['sourceHint']
            minimum += -(-int(quantity) // int(high)) * duration
            maximum += -(-int(quantity) // int(low)) * duration
        assert recipe['singleBatchInputAcquisitionMs']['minimumExact'] == str(minimum)
        assert recipe['singleBatchInputAcquisitionMs']['maximumExact'] == str(maximum)
        for row in recipe['yields']:
            level = int(row['levelExact'])
            expected = int(recipe['baseOutputExact']) * (1 + Fraction(max(0, level - 49), 1000))
            assert Fraction(int(row['expectedOutputNumeratorExact']), int(row['expectedOutputDenominatorExact'])) == expected
    for variant in ['normal', 'elite', 'endless', 'challenge']:
        for party in [1, 2, 5, 8]:
            rows = [x for x in report['dungeonScenarios'] if x['variant'] == variant and x['partySize'] == party]
            assert len(rows) == 12
            for field in ['combatBudgetBps', 'rewardMultiplierBps', 'completionXpExact', 'hpExact', 'challengeScoreExact']:
                assert all(int(a[field]) <= int(b[field]) for a, b in zip(rows, rows[1:])), (variant, party, field)
            assert all(10000 <= x['combatBudgetBps'] <= 60000 and x['rewardMultiplierBps'] <= 50000 for x in rows)
    for boss in report['worldBosses']:
        assert int(boss['respawnMillisecondsExact']) == 100 * int(boss['respawnTicksExact'])
        for axis, position in zip(['x', 'z'], boss['coordinatesMm']):
            q, r = divmod(position + 32000, 64000)
            assert boss['chunk']['coordinate'][axis] == q and boss['chunk']['localPositionMm'][axis] == r
        for scenario in boss['ttkScenarios']:
            dps = scenario['partySize'] * scenario['dpsPerPlayer']
            assert int(scenario['ttkMillisecondsExact']) == -(-1000 * int(boss['sourceHpExact']) // dps)
    for building in report['guildBuildings']:
        max_level = int(building['maximumLevelExact'])
        assert len(building['upgrades']) == max_level
        for resource, base in building['baseCostExact'].items():
            total = sum(int(upgrade['costExact'][resource]) for upgrade in building['upgrades'])
            assert total == int(base) * max_level * (max_level + 1) // 2
        for level, upgrade in enumerate(building['upgrades'], 1):
            for perk, maximum in building['maximumBonusesBps'].items():
                assert upgrade['projection']['bonusesBps'][perk] == maximum * level // max_level
    graph = set()
    for chunk in report['chunks']:
        cx, cz = chunk['coordinate']['x'], chunk['coordinate']['z']
        assert len(chunk['resources']) <= 8 and len(chunk['roadCells']) == 31
        for resource in chunk['resources']:
            assert all(4000 <= v < 60000 for v in resource['positionMm'].values())
        graph.update((cx * 16 + x, cz * 16 + z) for x, z in chunk['roadCells'])
    queue, visited = [min(graph)], set()
    while queue:
        vertex = queue.pop()
        if vertex in visited:
            continue
        visited.add(vertex)
        x, z = vertex
        queue.extend(v for v in [(x-1, z), (x+1, z), (x, z-1), (x, z+1)] if v in graph and v not in visited)
    assert visited == graph and len(graph) == 279
    for population in report['populations']:
        assert not population['overCapacitySectors']
        assert 0 < population['totalPopulation'] <= population['totalCapacity']
    for monster in report['monsters']:
        assert 2 <= monster['activeCount'] <= monster['maximumVisible'] <= 18
        assert 6 <= monster['encounterBudget'] <= 24
    for row in report['economy']:
        faucet, sink = int(row['faucetExact']), int(row['sinkExact'])
        assert row['sinkFaucetBps'] == 10000 * sink // faucet
        assert row['netIssuanceBps'] == 10000 * max(0, faucet - sink) // faucet
        assert (row['status'] == 'on_target') == (9200 <= row['sinkFaucetBps'] <= 10800)
    pity_expectations = {}
    for tier in report['pity']:
        chances = tier['chancesBps']
        assert len(chances) == tier['hardPityAttempt'] and chances[-1] == 10000
        assert all(0 < a <= b <= 10000 for a, b in zip(chances, chances[1:]))
        survival, expected = Fraction(1), Fraction(0)
        for chance in chances:
            expected += survival
            survival *= Fraction(10000 - chance, 10000)
        assert survival == 0 and 1 <= expected <= tier['hardPityAttempt']
        pity_expectations[tier['tier']] = float(expected)
    return {'status': 'local_independent_exact_oracle_pass', 'progressionLevelsChecked': 10000,
            'professions': len(report['professions']), 'recipes': len(report['recipes']),
            'dungeonScenarios': len(report['dungeonScenarios']), 'bossTtkScenarios': 60,
            'connectedRoadCells': len(graph), 'economyScenarios': len(report['economy']),
            'pityExpectedAttempts': pity_expectations, 'wolframExecuted': False, 'productionVerified': False}


if __name__ == '__main__':
    report_path = Path(sys.argv[1])
    raw = report_path.read_bytes()
    result = verify(json.loads(raw))
    result['inputSha256'] = hashlib.sha256(raw).hexdigest()
    print(json.dumps(result, sort_keys=True))
