import { Gamepad2, Hand, Swords, X } from "lucide-react";
import type { ControlSettings, SkillCommand } from "@shared/playerUiProtocol";
import { Ax1Modal } from "./Ax1Modal";
import { Ax1SkillBook } from "./Ax1SkillBook";
export function ControlsModal({ open, onClose, settings, pending, message, onBind, onAutoLoot, onAnalytics, onStartAuto }: {
  open: boolean; onClose: () => void; settings?: ControlSettings; pending: boolean; message?: string;
  onBind: (slot: number, command: SkillCommand) => void; onAutoLoot: () => void; onAnalytics: () => void; onStartAuto: () => void;
}) {
  return <Ax1Modal open={open} onClose={onClose} id="controls" title="Steuerung, Skills & Automatik"><section className="ax1-window w-full max-w-3xl bg-[#081a2e] border-2 border-amber-500/50 rounded-2xl p-5 text-gray-200 flex flex-col max-h-[92dvh] overflow-hidden"><header className="ax1-window-header flex justify-between gap-3 pb-3"><h3 className="font-serif text-amber-200 flex gap-2 items-center"><Gamepad2 />STEUERUNG & SKILLS</h3><button className="ax1-close" aria-label="Steuerung schließen" onClick={onClose}><X size={18} /></button></header>{message && <p className="ax1-notice" role="status">{message}</p>}<div className="overflow-y-auto min-h-0 custom-scrollbar space-y-4 py-3"><div className="grid sm:grid-cols-2 gap-3 text-xs"><p><Swords className="inline" size={16} />Angriff: <kbd>R</kbd> · Auto-Angriff: <kbd>T</kbd></p><p><Hand className="inline" size={16} />Interaktion: <kbd>F</kbd> · Skillplatz 3: <kbd>Leertaste</kbd></p><p>Bewegung: WASD · Ziel wählen: Tab</p><p>Inventar: I · Charakter: C · Quest-Buch: J</p></div><Ax1SkillBook settings={settings} pending={pending} onBind={onBind} /><section className="border border-gray-700 rounded-xl p-4 space-y-3"><button className="ax1-tab" aria-pressed={settings?.autoLoot ?? false} disabled={pending || !settings} onClick={onAutoLoot}>Auto-Loot {settings?.autoLoot ? "AN" : "AUS"}</button><p className="text-xs text-gray-400">Gewöhnliche und magische Beute wird automatisch eingesammelt. Seltene Funde nimmst du selbst auf.</p><button className="ax1-tab" aria-pressed={settings?.analyticsConsent ?? false} disabled={pending || !settings} onClick={onAnalytics}>Nutzungsanalyse {settings?.analyticsConsent ? "AN" : "AUS"}</button><p className="text-xs text-gray-400">Optional: Bestätigte Spielaktionen zur Verbesserung von Aurion an Amplitude senden, mit pseudonymer Kennung. Keine Namen, Chats, Eingaben oder Bildschirmaufnahmen. Jederzeit hier ausschaltbar.</p><button className="ax1-primary" disabled={pending} onClick={onStartAuto}>Menü schließen & Auto-Angriff starten</button><p className="text-xs text-gray-400">Greift in deiner begonnenen Begegnung an. Stoppt bei geöffneten Menüs, Verbindungsproblemen, ausgeblendetem Spiel oder abgeschlossener Begegnung. Nach der Rückkehr startest du erneut.</p></section></div></section></Ax1Modal>;
}
