/** -ax1 CraftingModal@d356881 (c13adeb): profession rail, recipe inspector and mastery tab.
 * Recipes consume real Aurion inventory; progress and outputs come from committed receipts. */
import { useState } from "react";
import { Award, BookOpen, Hammer, Package, Search, Sparkles, TrendingUp, X } from "lucide-react";
import type { inferRouterOutputs } from "@trpc/server";
import type { AppRouter } from "../../../../server/routers";
import type { PlayerUiReadback } from "@shared/playerUiProtocol";
import { Ax1Modal } from "./Ax1Modal";
type CraftingReadback = inferRouterOutputs<AppRouter>["crafting"]["read"];

export function CraftingModal({ isOpen, onClose, inventory, readback, pending, message, onCraft, onBonus }: {
  isOpen: boolean; onClose: () => void; inventory?: PlayerUiReadback; readback?: CraftingReadback;
  pending: boolean; message?: string; onCraft: (inputItemId: string) => void;
  onBonus: (batch: CraftingReadback["bonusOutputs"][number]) => void;
}) {
  const [tab, setTab] = useState<"crafting" | "progression">("crafting");
  const [search, setSearch] = useState("");
  const [selected, setSelected] = useState("");
  const inputs = inventory?.items.filter(i => i.version === "legacy" && i.definition === "aurion_spear" && i.quality === "normal" && i.status === "owned") ?? [];
  const input = inputs.find(i => i.id === selected) ?? inputs[0];
  return <Ax1Modal open={isOpen} onClose={onClose} id="crafting" title="Handwerk & Berufe"><section id="crafting-dialog" className="ax1-window w-full max-w-5xl bg-[#081a2e] border-2 border-amber-500/50 rounded-2xl p-4 sm:p-5 text-gray-200 flex flex-col max-h-[92dvh] overflow-hidden">
    <header className="ax1-window-header flex items-center justify-between gap-3 border-b border-gray-800 pb-3"><div className="flex items-center gap-3"><div className="ax1-crest"><Hammer /></div><div><h3 className="font-serif font-bold text-white">HANDWERK & BERUFE</h3><p className="text-xs text-gray-400">Schmiedekunst, Rezepte und Meisterschaft</p></div></div><button onClick={onClose} aria-label="Handwerk schließen" className="ax1-close"><X size={18} /></button></header>
    <nav className="flex flex-wrap gap-2 py-3" aria-label="Handwerksansicht"><button className="ax1-tab" aria-pressed={tab === "crafting"} onClick={() => setTab("crafting")}><Hammer size={14} />Rezepte & Schmiede</button><button className="ax1-tab" aria-pressed={tab === "progression"} onClick={() => setTab("progression")}><TrendingUp size={14} />Berufe & Meisterschaft</button></nav>
    {message && <p className="ax1-notice" role="status">{message}</p>}
    {!readback && <p role="status">Handwerk wird geladen.</p>}
    <div className="flex-1 overflow-y-auto min-h-0 custom-scrollbar py-3">{tab === "crafting" ? <div className="grid grid-cols-1 md:grid-cols-12 gap-4">
      <aside className="md:col-span-3 p-3 bg-black/50 border border-gray-800 rounded-xl space-y-3"><h4 className="text-xs font-serif text-amber-300 uppercase">Handwerksberufe</h4><button className="ax1-tab w-full" aria-pressed="true"><Hammer size={18} />Schmiedekunst</button><p className="text-xs text-gray-400">Verfügbare Rezepte deiner Schmiede.</p></aside>
      <section className="md:col-span-4 p-3 bg-black/50 border border-gray-800 rounded-xl space-y-3"><label className="flex gap-2 items-center"><Search size={16} /><input aria-label="Rezepte suchen" placeholder="Rezept suchen …" value={search} onChange={e => setSearch(e.target.value)} className="w-full min-w-0 text-xs" /></label>{"aurionspeer tempern schmiedekunst".includes(search.toLowerCase()) ? <article className="p-4 rounded-xl border border-amber-400/60 bg-[#081a2e]"><span className="text-3xl">⚒</span><h4 className="font-serif font-bold text-amber-200 mt-2">Aurionspeer tempern</h4><p className="text-xs text-gray-400 mt-2">Gewöhnlichen Speer zu einem magischen Aurionspeer veredeln.</p><span className="ax1-badge mt-3">{inputs.length} passende Gegenstände</span></article> : <p className="text-xs text-gray-500">Kein passendes Rezept.</p>}</section>
      <article className="md:col-span-5 p-4 bg-black/70 border border-gray-800 rounded-xl space-y-4"><h4 className="font-serif font-bold text-cyan-300 flex items-center gap-2"><BookOpen size={18} />Rezeptdetails</h4><div className="rounded-xl border border-gray-700 p-3"><b className="text-xs text-amber-200">Material: 1 gewöhnlicher Aurionspeer</b><p className="text-xs text-gray-400 mt-2">Der gewählte Speer wird verbraucht. Die Veredelung liefert einen magischen Speer und 6 Handwerks-EP.</p></div><label className="block text-xs space-y-2"><span>Eingesammelten Speer wählen</span><select className="w-full" value={input?.id ?? ""} disabled={pending || !inputs.length} onChange={e => setSelected(e.target.value)}>{!inputs.length && <option value="">Kein geeigneter Speer im Rucksack</option>}{inputs.map(i => <option key={i.id} value={i.id}>{i.name} · Stufe {i.levelExact} · {i.id.slice(-8)}</option>)}</select></label><button className="ax1-primary w-full" disabled={pending || !input || !readback} onClick={() => input && onCraft(input.id)}><Hammer size={15} />{pending ? "Herstellung wird bestätigt …" : "Speer tempern"}</button>{!inputs.length && <p className="text-xs text-gray-400">Sammle einen gewöhnlichen Aurionspeer ein. Ausgerüstete Speere musst du zuerst ablegen.</p>}</article>
    </div> : <div className="space-y-4"><section className="p-4 bg-black/60 border border-amber-500/30 rounded-xl"><h4 className="font-serif text-amber-300 flex gap-2"><Award size={18} />Deine Handwerkskunst</h4><p className="text-sm mt-3">{readback ? `Stufe ${readback.progression.progression.levelExact} · ${readback.progression.progression.totalXpExact} Handwerks-EP` : "Wird geladen"}</p></section><div className="grid sm:grid-cols-3 gap-3">{readback?.scopedMastery.map(m => <article className="p-4 bg-black/50 border border-gray-800 rounded-xl space-y-2" key={`${m.key.scopeType}:${m.key.scopeId}`}><h5 className="text-cyan-300 text-xs font-serif">{m.key.scopeType === "profession" ? "Schmiedekunst" : m.key.scopeType === "recipe" ? "Speerveredelung" : "Aurionspeer"}</h5><p className="text-sm">Stufe {m.progression.levelExact}</p><p className="text-xs text-gray-400">{m.progression.totalXpExact} EP · {m.lifetimeUsesExact} Ausführungen</p></article>)}</div></div>}
    <section className="mt-4 space-y-3"><h4 className="text-xs font-serif text-amber-300 flex gap-2"><Package size={16} />Hergestellte Gegenstände</h4><div className="grid sm:grid-cols-3 gap-2">{readback?.outputs.map(i => <article key={i.id} className="p-3 bg-black/50 border border-cyan-800 rounded-xl"><b className="text-xs text-cyan-200">{i.baseItemKey.replaceAll("_", " ")}</b><p className="text-xs text-gray-400">{i.quality} · Stufe {i.itemLevel}</p></article>)}</div>{readback && !readback.outputs.length && <p className="text-xs text-gray-500">Noch keine hergestellten Gegenstände im Rucksack.</p>}{readback?.bonusOutputs.map(batch => <article key={batch.professionReceiptId} className="p-3 border border-amber-500/30 rounded-xl space-y-2"><p className="text-xs">{batch.remainingQuantityExact} zusätzliche Gegenstände stehen bereit.</p><button className="ax1-tab" disabled={pending} onClick={() => onBonus(batch)}><Sparkles size={14} />Bonus ins Inventar übernehmen</button></article>)}</section>
    </div>
  </section></Ax1Modal>;
}
