import { createHash } from "node:crypto";
import { AURION_WORLD_GRAPH_GRAMMAR_COMPILER_VERSION, AURION_WORLD_GRAPH_GRAMMAR_PROTOCOL, AURION_WORLD_GRAPH_STREAM_POLICY_VERSION, WORLD_GRAPH_LAYERS, type CanonicalWorldGraph, type DeterministicWorldGraphGrammarCompilerInput, type WorldGraphLayer, type WorldGraphRule, type WorldGraphNodeInput, type WorldGraphGrammarCompilation } from "@shared/deterministicWorldGraphGrammarProtocol";
const REVISION = /^[a-f0-9]{40}$/;
const SHA256 = /^sha256:[a-f0-9]{64}$/;
const MAX_NODES_DEFAULT = 4096;
const MAX_EDGES_DEFAULT = 8192;
const LAYER_RANK: Readonly<Record<WorldGraphLayer, number>> = Object.freeze(Object.fromEntries(WORLD_GRAPH_LAYERS.map((layer, index) => [layer, index])) as Record<WorldGraphLayer, number>);
function fail(message: string): never { throw new Error("WORLD_GRAPH_GRAMMAR_" + message); }
function cmp(a: string, b: string): number { return a < b ? -1 : a > b ? 1 : 0; }
function canonical(value: unknown): string { if (value === null || value === undefined) return "null"; if (typeof value === "string" || typeof value === "boolean" || typeof value === "number") return JSON.stringify(value); if (Array.isArray(value)) return "[" + value.map(canonical).join(",") + "]"; const record = value as Record<string, unknown>; return "{" + Object.keys(record).sort(cmp).map(key => JSON.stringify(key) + ":" + canonical(record[key])).join(",") + "}"; }
function sha(value: string): string { return "sha256:" + createHash("sha256").update(value, "utf8").digest("hex"); }
function assertIdentifier(value: string, field: string): void { if (!value || value.length > 256 || !/^[A-Za-z0-9][A-Za-z0-9._:-]*$/.test(value)) fail("INVALID_IDENTIFIER_" + field); }
function assertCoordinate(value: number, field: string): void { if (!Number.isSafeInteger(value)) fail("INVALID_COORDINATE_" + field); }
function canonicalTags(tags: readonly string[]): readonly string[] { const normalized = tags.map(tag => tag.trim()); if (normalized.some(tag => !tag || tag.length > 128)) fail("INVALID_TAG"); return Object.freeze([...new Set(normalized)].sort(cmp)); }
function validateRule(rule: WorldGraphRule): void { assertIdentifier(rule.id, "RULE"); if (!Number.isSafeInteger(rule.maxChildren) || rule.maxChildren < 1 || rule.maxChildren > 4096) fail("INVALID_MAX_CHILDREN"); if (rule.parentLayer && LAYER_RANK[rule.parentLayer] >= LAYER_RANK[rule.layer]) fail("INVALID_PARENT_LAYER_ORDER"); }
function streamId(seed: string, revision: string, grammarVersion: string, layer: WorldGraphLayer, ruleId: string, nodeId: string): string { return sha(["aurion.world-graph.stream.v1", seed, revision, grammarVersion, layer, ruleId, nodeId].join("::")); }
function canonicalNode(input: WorldGraphNodeInput, rule: WorldGraphRule, worldSeedHash: string, sourceRevision: string, grammarVersion: string, parentHash: string | null): CanonicalWorldGraph["nodes"][number] { const tags = canonicalTags(input.tags); const derivedStream = streamId(worldSeedHash, sourceRevision, grammarVersion, input.layer, input.ruleId, input.nodeId); const constraintHash = sha(canonical({ domain: "aurion.world-graph.node-constraints.v1", nodeId: input.nodeId, layer: input.layer, ruleId: input.ruleId, parentHash, coordinate: input.coordinate, tags })); const nodeHash = sha(canonical({ domain: "aurion.world-graph.node.v1", nodeId: input.nodeId, layer: input.layer, ruleId: input.ruleId, parentId: input.parentId ?? null, coordinate: input.coordinate, tags, streamId: derivedStream, constraintHash })); return Object.freeze({ nodeId: input.nodeId, layer: input.layer, ruleId: input.ruleId, parentId: input.parentId ?? null, coordinate: Object.freeze({ x: input.coordinate.x, z: input.coordinate.z }), tags, streamId: derivedStream, constraintHash, nodeHash }); }
function canonicalEdge(input: DeterministicWorldGraphGrammarCompilerInput["edges"][number], nodes: ReadonlyMap<string, CanonicalWorldGraph["nodes"][number]>): CanonicalWorldGraph["edges"][number] { const from = nodes.get(input.fromNodeId); const to = nodes.get(input.toNodeId); if (!from || !to) fail("EDGE_NODE_REFERENCE_MISSING_" + input.edgeId); return Object.freeze({ edgeId: input.edgeId, kind: input.kind, fromNodeId: input.fromNodeId, toNodeId: input.toNodeId, edgeHash: sha(canonical({ domain: "aurion.world-graph.edge.v1", edgeId: input.edgeId, kind: input.kind, fromNodeHash: from.nodeHash, toNodeHash: to.nodeHash })) }); }
function layerHash(layer: WorldGraphLayer, nodes: readonly CanonicalWorldGraph["nodes"][number][], edges: readonly CanonicalWorldGraph["edges"][number][]): string { const nodeHashes = nodes.filter(node => node.layer === layer).map(node => node.nodeHash).sort(cmp); const edgeHashes = edges.filter(edge => { const from = nodes.find(node => node.nodeId === edge.fromNodeId); const to = nodes.find(node => node.nodeId === edge.toNodeId); return from?.layer === layer || to?.layer === layer; }).map(edge => edge.edgeHash).sort(cmp); return sha(canonical({ domain: "aurion.world-graph.layer.v1", layer, nodeHashes, edgeHashes })); }
export function compileDeterministicWorldGraphGrammar(input: DeterministicWorldGraphGrammarCompilerInput): WorldGraphGrammarCompilation {
  if (!SHA256.test(input.worldSeedHash) || !SHA256.test(input.rulesetHash)) fail("HASH_INVALID");
  if (!REVISION.test(input.worldGenerationRevision) || !REVISION.test(input.sourceRevision)) fail("REVISION_INVALID");
  assertIdentifier(input.worldId, "WORLD"); assertIdentifier(input.grammar.grammarId, "GRAMMAR"); assertIdentifier(input.grammar.grammarVersion, "GRAMMAR_VERSION");
  const maxNodes = input.maxNodes ?? MAX_NODES_DEFAULT; const maxEdges = input.maxEdges ?? MAX_EDGES_DEFAULT;
  if (!Number.isSafeInteger(maxNodes) || maxNodes < 1 || maxNodes > MAX_NODES_DEFAULT) fail("MAX_NODES_INVALID"); if (!Number.isSafeInteger(maxEdges) || maxEdges < 1 || maxEdges > MAX_EDGES_DEFAULT * 2) fail("MAX_EDGES_INVALID"); if (!input.nodes.length) fail("EMPTY_GRAPH"); if (input.nodes.length > maxNodes) fail("NODE_BUDGET_EXCEEDED"); if (input.edges.length > maxEdges) fail("EDGE_BUDGET_EXCEEDED");
  const ruleById = new Map<string, WorldGraphRule>(); for (const rule of input.grammar.rules) { if (ruleById.has(rule.id)) fail("DUPLICATE_RULE_" + rule.id); validateRule(rule); ruleById.set(rule.id, rule); } if (!input.grammar.rules.some(rule => rule.layer === input.grammar.rootLayer)) fail("ROOT_LAYER_RULE_MISSING");
  const inputIds = new Set<string>(); for (const node of input.nodes) { if (inputIds.has(node.nodeId)) fail("DUPLICATE_NODE_" + node.nodeId); inputIds.add(node.nodeId); assertIdentifier(node.nodeId, "NODE"); if (!WORLD_GRAPH_LAYERS.includes(node.layer)) fail("INVALID_NODE_LAYER"); assertIdentifier(node.ruleId, "NODE_RULE"); const rule = ruleById.get(node.ruleId); if (!rule) fail("NODE_RULE_MISSING_" + node.ruleId); if (rule.layer !== node.layer) fail("NODE_RULE_LAYER_MISMATCH_" + node.nodeId); assertCoordinate(node.coordinate.x, "X"); assertCoordinate(node.coordinate.z, "Z"); if (node.parentId === node.nodeId) fail("SELF_PARENT_" + node.nodeId); }
  const rawNodeById = new Map(input.nodes.map(node => [node.nodeId, node] as const));
  const childCounts = new Map<string, number>();
  for (const node of input.nodes) if (node.parentId) childCounts.set(node.parentId, (childCounts.get(node.parentId) ?? 0) + 1);
  for (const [nodeId, count] of childCounts) { const node = rawNodeById.get(nodeId)!; const rule = ruleById.get(node.ruleId)!; if (count > rule.maxChildren) fail("CHILD_BUDGET_EXCEEDED_" + nodeId); }
  for (const node of input.nodes) { if (!node.parentId) continue; const parent = rawNodeById.get(node.parentId); if (!parent) fail("PARENT_REFERENCE_MISSING_" + node.nodeId); const rule = ruleById.get(node.ruleId)!; if (rule.parentLayer !== parent.layer) fail("PARENT_LAYER_MISMATCH_" + node.nodeId); }
  const parentMap = new Map(input.nodes.map(node => [node.nodeId, node.parentId ?? null] as const));
  for (const node of input.nodes) { let cursor = parentMap.get(node.nodeId) ?? null; const seen = new Set<string>(); while (cursor) { if (seen.has(cursor)) fail("PARENT_CYCLE"); seen.add(cursor); cursor = parentMap.get(cursor) ?? null; } }
  const sortedInputs = [...input.nodes].sort((a, b) => LAYER_RANK[a.layer] - LAYER_RANK[b.layer] || cmp(a.nodeId, b.nodeId));
  const canonicalNodes: CanonicalWorldGraph["nodes"][number][] = []; const parentHashes = new Map<string, string | null>();
  for (const node of sortedInputs) { const parentNode = node.parentId ? rawNodeById.get(node.parentId) : null; const parentHash = parentNode ? canonicalNodes.find(candidate => candidate.nodeId === parentNode.nodeId)?.nodeHash ?? null : null; const next = canonicalNode(node, ruleById.get(node.ruleId)!, input.worldSeedHash, input.sourceRevision, input.grammar.grammarVersion, parentHash); canonicalNodes.push(next); parentHashes.set(node.nodeId, parentHash); }
  const nodeById = new Map(canonicalNodes.map(node => [node.nodeId, node] as const));
  const edgeIds = new Set<string>(); for (const edge of input.edges) { if (edgeIds.has(edge.edgeId)) fail("DUPLICATE_EDGE_" + edge.edgeId); edgeIds.add(edge.edgeId); assertIdentifier(edge.edgeId, "EDGE"); if (edge.fromNodeId === edge.toNodeId) fail("SELF_EDGE_" + edge.edgeId); }
  const canonicalEdges = input.edges.map(edge => canonicalEdge(edge, nodeById)).sort((a, b) => cmp(a.edgeId, b.edgeId));
  const layerHashes = Object.fromEntries(WORLD_GRAPH_LAYERS.map(layer => [layer, layerHash(layer, canonicalNodes, canonicalEdges)])) as Record<WorldGraphLayer, string>;
  const parentHashRows = Object.freeze(canonicalNodes.map(node => Object.freeze({ nodeId: node.nodeId, parentHash: parentHashes.get(node.nodeId) ?? null })).sort((a, b) => cmp(a.nodeId, b.nodeId)));
  const canonicalGraph = Object.freeze({ protocol: AURION_WORLD_GRAPH_GRAMMAR_PROTOCOL, compilerVersion: AURION_WORLD_GRAPH_GRAMMAR_COMPILER_VERSION, streamPolicyVersion: AURION_WORLD_GRAPH_STREAM_POLICY_VERSION, worldId: input.worldId, worldSeedHash: input.worldSeedHash, worldGenerationRevision: input.worldGenerationRevision, rulesetHash: input.rulesetHash, grammarId: input.grammar.grammarId, grammarVersion: input.grammar.grammarVersion, sourceRevision: input.sourceRevision, nodes: Object.freeze([...canonicalNodes]), edges: Object.freeze([...canonicalEdges]), layerHashes: Object.freeze(layerHashes), parentHashes: parentHashRows });
  const canonicalGraphJson = canonical(canonicalGraph); const canonicalGraphHash = sha("aurion.world-graph.canonical.v1::" + canonicalGraphJson);
  const streamRootHash = sha("aurion.world-graph.stream-root.v1::" + canonical(canonicalNodes.map(node => [node.nodeId, node.streamId]).sort((a, b) => cmp(String(a[0]), String(b[0])))));
  const inputHash = sha("aurion.world-graph.input.v1::" + canonical({ worldId: input.worldId, worldSeedHash: input.worldSeedHash, worldGenerationRevision: input.worldGenerationRevision, rulesetHash: input.rulesetHash, grammar: { ...input.grammar, rules: [...input.grammar.rules].sort((a, b) => cmp(a.id, b.id)) }, nodes: [...input.nodes].map(node => ({ ...node, tags: canonicalTags(node.tags) })).sort((a, b) => cmp(a.nodeId, b.nodeId)), edges: [...input.edges].sort((a, b) => cmp(a.edgeId, b.edgeId)), sourceRevision: input.sourceRevision }));
  const layerNodeCounts = Object.fromEntries(WORLD_GRAPH_LAYERS.map(layer => [layer, canonicalNodes.filter(node => node.layer === layer).length])) as Record<WorldGraphLayer, number>;
  return Object.freeze({ inputHash, canonicalGraph, canonicalGraphJson, canonicalGraphHash, streamRootHash, stats: Object.freeze({ nodeCount: canonicalNodes.length, edgeCount: canonicalEdges.length, layerNodeCounts: Object.freeze(layerNodeCounts) }) });
}