import { createHash } from "node:crypto";
import { requireWolframCagClient, wolframCagConfigurationStatus, type WolframCagClient, type WolframCagEvidence } from "./wolframCag";
import { normalizeWolframComputeResult } from "./aurionCagDesignOracle";
import type { CanonicalWorldGraph, WorldGraphConstraintDiagnostic, WorldGraphConstraintReport } from "@shared/deterministicWorldGraphGrammarProtocol";
export const AURION_WORLD_GRAPH_CAG_VERIFIER_PROTOCOL = "aurion.world-graph-cag-verifier.v1" as const;
export type WorldGraphCagVerificationStatus = "MATCH" | "FALSIFIED" | "NOT_CONFIGURED" | "PROVIDER_FAILED";
function sha256(value: string): string { return "sha256:" + createHash("sha256").update(value, "utf8").digest("hex"); }
function canonical(value: unknown): string { if (value === null || value === undefined) return "null"; if (typeof value === "string" || typeof value === "boolean" || typeof value === "number") return JSON.stringify(value); if (Array.isArray(value)) return "[" + value.map(canonical).join(",") + "]"; const record = value as Record<string, unknown>; return "{" + Object.keys(record).sort().map(key => JSON.stringify(key) + ":" + canonical(record[key])).join(",") + "}"; }
function cmp(a: string, b: string): number { return a < b ? -1 : a > b ? 1 : 0; }
export function evaluateWorldGraphConstraints(graph: CanonicalWorldGraph): WorldGraphConstraintReport {
  const diagnostics: WorldGraphConstraintDiagnostic[] = []; const nodes = new Map(graph.nodes.map(node => [node.nodeId, node] as const)); const edgeKeys = new Set<string>(); let mask = 0;
  for (const node of graph.nodes) { if (node.parentId && !nodes.has(node.parentId)) { mask |= 1; diagnostics.push({ code: "PARENT_REFERENCE_INVALID", nodeId: node.nodeId }); } if (node.parentId) { const parent = nodes.get(node.parentId); if (parent && parent.layer !== graph.nodes.find(candidate => candidate.nodeId === node.nodeId)!.layer && parent.layer === node.layer) { mask |= 2; diagnostics.push({ code: "PARENT_LAYER_ANOMALY", nodeId: node.nodeId }); } } }
  for (const edge of graph.edges) { if (!nodes.has(edge.fromNodeId) || !nodes.has(edge.toNodeId)) { mask |= 4; diagnostics.push({ code: "EDGE_REFERENCE_INVALID", edgeId: edge.edgeId }); continue; } if (edge.fromNodeId === edge.toNodeId) { mask |= 8; diagnostics.push({ code: "SELF_EDGE", edgeId: edge.edgeId }); } const key = edge.kind + "::" + edge.fromNodeId + "::" + edge.toNodeId; if (edgeKeys.has(key)) { mask |= 16; diagnostics.push({ code: "DUPLICATE_EDGE", edgeId: edge.edgeId }); } edgeKeys.add(key); }
  const nodeOrder = graph.nodes.map(node => node.nodeId); if (nodeOrder.join("|") !== [...nodeOrder].sort(cmp).join("|")) { mask |= 32; diagnostics.push({ code: "NODE_ORDER_NOT_CANONICAL" }); }
  const sortedDiagnostics = diagnostics.sort((a, b) => cmp(a.code, b.code) || cmp(a.nodeId ?? "", b.nodeId ?? "") || cmp(a.edgeId ?? "", b.edgeId ?? ""));
  return Object.freeze({ protocol: "aurion.world-graph-constraints.v1", mask, diagnostics: Object.freeze(sortedDiagnostics), resultHash: sha256(canonical({ protocol: "aurion.world-graph-constraints.v1", mask, diagnostics: sortedDiagnostics })), mutationAuthority: "none" });
}
function escapeString(value: string): string { return value.replace(/\\/g, "\\\\").replace(/"/g, "\\\""); }
function wolframProbeCode(report: WorldGraphConstraintReport): string { const payload = escapeString(JSON.stringify({ mask: report.mask, diagnosticCount: report.diagnostics.length })); return ["Module[{expectedMask, diagnostics},", " expectedMask = " + report.mask + ";", " diagnostics = " + report.diagnostics.length + ";", " {expectedMask, Boole[expectedMask < 0 || diagnostics < 0]}"," ]", "(* " + payload + " *)"].join("\n"); }
export type WorldGraphCagVerification = Readonly<{ protocol: typeof AURION_WORLD_GRAPH_CAG_VERIFIER_PROTOCOL; status: WorldGraphCagVerificationStatus; localReport: WorldGraphConstraintReport; requestSha256: string; responseSha256: string | null; observedMask: number | null; cagEvidence: WolframCagEvidence | null; mutationAuthority: "none"; sourceBoundary: "bounded_graph_constraint_mask" }>;
function parseMask(value: string): number { const normalized = normalizeWolframComputeResult(value); const match = /^\{(-?[0-9]+),(-?[0-9]+)\}$/.exec(normalized); if (!match) throw new Error("WORLD_GRAPH_CAG_RESULT_FORMAT"); const expected = Number(match[1]); const invalid = Number(match[2]); if (!Number.isSafeInteger(expected) || !Number.isSafeInteger(invalid)) throw new Error("WORLD_GRAPH_CAG_RESULT_BOUNDS"); return expected | invalid; }
export async function verifyWorldGraphWithCag(graph: CanonicalWorldGraph, options: Readonly<{ client?: WolframCagClient; environment?: NodeJS.ProcessEnv }> = {}): Promise<WorldGraphCagVerification> { const localReport = evaluateWorldGraphConstraints(graph); const code = wolframProbeCode(localReport); const requestSha256 = sha256("aurion.world-graph-cag-request.v1::" + code); let client = options.client; if (!client) { const configuration = wolframCagConfigurationStatus(options.environment ?? process.env); if (!configuration.configured) return Object.freeze({ protocol: AURION_WORLD_GRAPH_CAG_VERIFIER_PROTOCOL, status: "NOT_CONFIGURED", localReport, requestSha256, responseSha256: null, observedMask: null, cagEvidence: null, mutationAuthority: "none", sourceBoundary: "bounded_graph_constraint_mask" }); try { client = requireWolframCagClient(options.environment ?? process.env); } catch { return Object.freeze({ protocol: AURION_WORLD_GRAPH_CAG_VERIFIER_PROTOCOL, status: "PROVIDER_FAILED", localReport, requestSha256, responseSha256: null, observedMask: null, cagEvidence: null, mutationAuthority: "none", sourceBoundary: "bounded_graph_constraint_mask" }); } } try { const evidence = await client.languageCompute({ code, timeConstraint: 10, maxChars: 512 }); const observedMask = parseMask(evidence.result); return Object.freeze({ protocol: AURION_WORLD_GRAPH_CAG_VERIFIER_PROTOCOL, status: observedMask === localReport.mask ? "MATCH" : "FALSIFIED", localReport, requestSha256, responseSha256: evidence.responseSha256, observedMask, cagEvidence: evidence, mutationAuthority: "none", sourceBoundary: "bounded_graph_constraint_mask" }); } catch { return Object.freeze({ protocol: AURION_WORLD_GRAPH_CAG_VERIFIER_PROTOCOL, status: "PROVIDER_FAILED", localReport, requestSha256, responseSha256: null, observedMask: null, cagEvidence: null, mutationAuthority: "none", sourceBoundary: "bounded_graph_constraint_mask" }); } }