import { expect, test, type Page } from "@playwright/test";
import { createPool, type RowDataPacket } from "mysql2/promise";
import { execFileSync } from "node:child_process";
import type { PlayerUiReadback } from "../shared/playerUiProtocol";

test.skip(process.env.AURION_UI_E2E !== "1", "Isolated AX1 runtime required");
async function rpc<T>(page: Page, procedure: string): Promise<T> {
  const response = await page.request.get(`/api/trpc/${procedure}`);
  expect(response.ok()).toBe(true);
  const body = await response.json();
  expect(body.error).toBeUndefined();
  return body.result.data.json;
}
for (const viewport of [{ name: "phone", width: 412, height: 915 }, { name: "tablet", width: 800, height: 1280 }, { name: "desktop", width: 1440, height: 1000 }]) {
  test(`AX1 real controls, unarmed healer, earned inventory and confirmed attacks on ${viewport.name}`, async ({ page, baseURL }, info) => {
    test.setTimeout(240_000);
    expect(baseURL).toBe("http://127.0.0.1:3000");
    const url = new URL(process.env.DATABASE_URL!);
    expect(url.hostname).toBe("127.0.0.1"); expect(url.pathname).toBe("/aurion_group_test");
    const pool = createPool(process.env.DATABASE_URL!);
    const errors: string[] = []; page.on("pageerror", error => errors.push(error.message));
    try {
      await page.setViewportSize(viewport); await page.goto("/");
      await page.getByRole("button", { name: "KONTO ANLEGEN / ANMELDEN", exact: true }).click();
      const dialog = page.getByRole("dialog");
      await dialog.getByRole("tab", { name: "Konto anlegen", exact: true }).click();
      const handle = `ax1_ui_${viewport.name}`;
      await dialog.getByLabel("Rufname", { exact: true }).fill(handle);
      await dialog.getByLabel("Passwort", { exact: true }).fill("Aurion-isolated-ui-regression!");
      await dialog.getByRole("button", { name: "Aurion-Konto erstellen", exact: true }).click();
      await page.getByRole("button", { name: /ALLEIN DIE STERNWARTE BETRETEN/ }).click();
      await page.getByRole("button", { name: "IN DIE OPEN WORLD", exact: true }).click();
      const runtime = page.getByTestId("xaurion-open-world-runtime");
      const hud = page.getByTestId("authoritative-world-hud");
      await expect(runtime.getByText("BEWEGUNG VERBUNDEN", { exact: true })).toBeVisible({ timeout: 45_000 });
      const environment=page.getByTestId("world-assets-evidence");
      const assetEvidence=async()=>JSON.parse(await environment.getAttribute("data-presentation")||"{}");
      await expect.poll(async()=>(await assetEvidence()).rendered,{timeout:60_000}).toBeGreaterThan(0);
      await expect.poll(async()=>(await assetEvidence()).loading,{timeout:60_000}).toBe(0);
      expect((await assetEvidence()).failed).toBe(0);
      expect((await assetEvidence()).planned).toBe(108);
      await page.screenshot({path:info.outputPath(`${viewport.name}-world-assets.png`)});
      const initial = await rpc<PlayerUiReadback>(page, "player.ui");
      expect(initial.items).toEqual([]);
      const userId = initial.userId;
      const confirmed = () => expect(dialog.getByText("Änderung vom Server bestätigt.", { exact: true })).toBeVisible();
      await hud.getByRole("button", { name: "Inventar", exact: true }).click();
      await expect(dialog.getByText("Keine Gegenstände in dieser Ansicht.", { exact: true })).toBeVisible();
      await dialog.getByRole("button", { name: "Auto-Loot AN", exact: true }).click(); await confirmed();
      await page.screenshot({ path: info.outputPath(`${viewport.name}-inventory.png`) });
      await dialog.getByRole("button", { name: "Inventar schließen", exact: true }).click();
      await hud.getByRole("button", { name: "Charakter", exact: true }).click();
      await expect(dialog.getByRole("button", { name: "Hüter", exact: true })).toBeDisabled();
      await dialog.getByRole("button", { name: "Skills & Meisterschaft", exact: true }).click();
      await dialog.getByLabel("Heilendes Licht", { exact: true }).click(); await confirmed();
      await expect(dialog.getByLabel("Heilendes Licht", { exact: true })).toBeChecked();
      const group = await rpc<any>(page, "groups.read");
      expect(group.player.skills).toContain("mending_light"); expect(group.qualification.roles).toContain("healer");
      const [unarmed] = await pool.query<RowDataPacket[]>("SELECT selectedClass FROM playerProfiles WHERE userId=?", [userId]);
      const [equipment] = await pool.query<RowDataPacket[]>("SELECT * FROM aurionEquipmentSlots WHERE userId=?", [userId]);
      expect(unarmed[0].selectedClass).toBe("unbound"); expect(equipment).toHaveLength(0);
      await dialog.getByLabel("Skillplatz 1", { exact: true }).selectOption("9"); await confirmed();
      await expect(dialog.getByLabel("Skillplatz 1", { exact: true })).toHaveValue("9");
      await page.screenshot({ path: info.outputPath(`${viewport.name}-skills.png`) });
      await dialog.getByRole("button", { name: "Charakter schließen", exact: true }).click();
      await hud.getByRole("button", { name: "Aufträge & Kontakte", exact: true }).click();
      await dialog.getByRole("button", { name: "Bei Lyra annehmen", exact: true }).click(); await confirmed();
      await page.screenshot({ path: info.outputPath(`${viewport.name}-quests.png`) });
      await dialog.getByRole("button", { name: "Quest-Buch schließen", exact: true }).click();
      await hud.getByRole("button", { name: "Begegnungen", exact: true }).click();
      await dialog.getByRole("button", { name: "Sternwarte Asterion beginnen", exact: true }).click();
      await expect(dialog).toHaveCount(0);
      const attack = hud.getByRole("button", { name: "Angriff", exact: true });
      // Radix correctly hides the background HUD from assistive technology while a
      // modal is open; inspect its state without requiring it to remain accessible.
      const auto = hud.getByRole("button", { name: "Auto-Angriff", exact: true, includeHidden: true });
      await page.getByTestId("glb-presentation").evaluate(element => {
        const samples: unknown[] = []; (window as any).__ax1AttackSamples = samples;
        new MutationObserver(() => { const sample=JSON.parse(element.getAttribute("data-attack")||"{}"); if(sample.attacking && sample.visible && samples.length<30)samples.push(sample); }).observe(element,{attributes:true,attributeFilter:["data-attack"]});
      });
      const action = page.waitForResponse(r => r.url().includes("gameplay.act") && r.status() === 200);
      await attack.click(); await action;
      await expect(page.locator("#three-viewport")).toHaveAttribute("data-confirmed-attack-receipt", /.+/);
      await expect.poll(()=>page.evaluate(()=>(window as any).__ax1AttackSamples.length),{timeout:10_000}).toBeGreaterThan(1);
      const animation=await page.evaluate(()=>(window as any).__ax1AttackSamples);
      expect(new Set(animation.map((sample:any)=>JSON.stringify(sample.arm))).size).toBeGreaterThan(1);
      const [boss]=await pool.query<RowDataPacket[]>("SELECT bossHp,maxBossHp FROM gameplaySessions WHERE userId=?",[userId]);
      expect(boss[0].bossHp).toBeLessThan(boss[0].maxBossHp);
      const receipts = async () => { const [rows] = await pool.query<RowDataPacket[]>("SELECT sequence,command,damage FROM gameplayActionReceipts WHERE userId=? ORDER BY sequence", [userId]); return rows; };
      await expect.poll(async () => (await receipts()).length).toBe(1);
      expect((await receipts())[0]).toMatchObject({ command: "F" });
      expect(Number((await receipts())[0].damage)).toBeGreaterThan(0);
      await expect(auto).toBeEnabled(); await auto.click();
      await expect.poll(async () => (await receipts()).length).toBeGreaterThan(1);
      await hud.getByRole("button", { name: "Inventar", exact: true }).click();
      await expect(auto).toHaveAttribute("aria-pressed", "false");
      // An in-flight command may finish, but no new command may start behind this menu.
      await expect.poll(async () => { const before = (await receipts()).length; await page.waitForTimeout(1300); return (await receipts()).length === before; }).toBe(true);
      await dialog.getByRole("button", { name: "Inventar schließen", exact: true }).click();
      await auto.click();
      await expect.poll(async () => { const [rows] = await pool.query<RowDataPacket[]>("SELECT status FROM gameplaySessions WHERE userId=? ORDER BY startedAt DESC LIMIT 1", [userId]); return rows[0]?.status; }, { timeout: 70_000 }).toBe("completed");
      await expect(auto).toHaveAttribute("aria-pressed", "false");
      const actions = await receipts();
      expect(actions.map(row => row.sequence)).toEqual(actions.map((_, i) => i + 1));
      await hud.getByRole("button", { name: "Aufträge & Kontakte", exact: true }).click();
      await dialog.getByRole("button", { name: "Bei Lyra abgeben", exact: true }).click(); await confirmed();
      await dialog.getByRole("button", { name: "Quest-Buch schließen", exact: true }).click();
      const loot = await rpc<PlayerUiReadback>(page, "player.ui");
      expect(loot.items.length).toBeGreaterThan(0); expect(loot.items.every(i => i.status === "pending_pickup")).toBe(true);
      await hud.getByRole("button", { name: "Inventar", exact: true }).click();
      const item = loot.items.find(i => i.slot)!; expect(item).toBeDefined();
      await dialog.getByTestId(`bag-${item.id}`).click();
      await dialog.getByRole("button", { name: "Beute einsammeln", exact: true }).click(); await confirmed();
      await dialog.getByRole("button", { name: "Ausrüsten", exact: true }).click(); await confirmed();
      expect((await rpc<PlayerUiReadback>(page, "player.ui")).equipment).toContainEqual({ id: item.id, version: item.version, slot: item.slot });
      await page.screenshot({ path: info.outputPath(`${viewport.name}-paperdoll.png`) });
      await dialog.getByRole("button", { name: "Ablegen", exact: true }).click(); await confirmed();
      await dialog.getByRole("button", { name: "Auto-Loot AUS", exact: true }).click(); await confirmed();
      // Explicit isolated fixtures exercise the real loot persistence function with the
      // accepted encounter receipt. These two drops are not claimed as earned rewards.
      const [accepted] = await pool.query<RowDataPacket[]>("SELECT id,expeditionKey,seedDigest FROM expeditionResultReceipts WHERE userId=? AND status='accepted' ORDER BY createdAt DESC LIMIT 1", [userId]);
      expect(accepted).toHaveLength(1);
      const fixtureInput = { userId, resultReceiptId: accepted[0].id, expeditionKey: accepted[0].expeditionKey, seedDigest: accepted[0].seedDigest };
      const fixtureOutput = execFileSync(process.execPath, ["--import", "tsx", "--input-type=module", "-e", `
        const url = new URL(process.env.DATABASE_URL);
        if (process.env.AURION_UI_E2E !== "1" || url.hostname !== "127.0.0.1" || url.pathname !== "/aurion_group_test") throw Error("ISOLATED_UI_DATABASE_REQUIRED");
        const { createLootDrop } = await import("./server/db.ts");
        const input = JSON.parse(process.argv[1]);
        const drops = [];
        for (const qualityRoll of [9996, 400]) drops.push(await createLootDrop({ ...input, treasureClass: "asterion_t2_weapons", qualityRoll, affixRoll: 0, magicFind: 0, itemLevel: 1, idempotencyKey: "ax1-ui-fixture:" + input.userId + ":" + qualityRoll }));
        console.log("AX1_FIXTURE_JSON=" + JSON.stringify(drops)); process.exit(0);
      `, JSON.stringify(fixtureInput)], { encoding: "utf8", timeout: 30_000 });
      const fixtureDrops: { itemId: string; receiptId: string; quality: string }[] = JSON.parse(fixtureOutput.split("\n").find(line => line.startsWith("AX1_FIXTURE_JSON="))!.slice("AX1_FIXTURE_JSON=".length));
      const normal = fixtureDrops.find(drop => drop.quality === "normal")!;
      const rare = fixtureDrops.find(drop => drop.quality === "rare")!;
      const autoLootReadback = await rpc<PlayerUiReadback>(page, "player.ui");
      expect(autoLootReadback.items.find(i => i.id === normal.itemId)).toMatchObject({ status: "owned", definition: "aurion_spear" });
      expect(autoLootReadback.items.find(i => i.id === rare.itemId)).toMatchObject({ status: "pending_pickup" });
      await dialog.getByRole("button", { name: "Auto-Loot AN", exact: true }).click(); await confirmed();
      await dialog.getByTestId(`bag-${rare.itemId}`).click();
      await dialog.getByRole("button", { name: "Beute einsammeln", exact: true }).click(); await confirmed();
      expect((await rpc<PlayerUiReadback>(page, "player.ui")).items.find(i => i.id === rare.itemId)?.status).toBe("owned");
      await dialog.getByRole("button", { name: "Handwerk öffnen", exact: true }).click();
      await expect(dialog.getByText("HANDWERK & BERUFE", { exact: true })).toBeVisible();
      await dialog.getByLabel("Eingesammelten Speer wählen", { exact: true }).selectOption(normal.itemId);
      await dialog.getByRole("button", { name: "Speer tempern", exact: true }).click(); await confirmed();
      const crafting = await rpc<any>(page, "crafting.read");
      expect(crafting.receipts).toHaveLength(1);
      expect(crafting.outputs).toHaveLength(1);
      expect(crafting.outputs[0]).toMatchObject({ baseItemKey: "aurion_spear", quality: "magic" });
      expect(crafting.progression.progression.totalXpExact).toBe("6");
      const [consumed] = await pool.query<RowDataPacket[]>("SELECT status FROM itemInstances WHERE id=?", [normal.itemId]);
      expect(consumed[0].status).toBe("consumed");
      await dialog.getByRole("button", { name: "Berufe & Meisterschaft", exact: true }).click();
      await expect(dialog.getByText(/6 Handwerks-EP/)).toBeVisible();
      await page.screenshot({ path: info.outputPath(`${viewport.name}-crafting.png`) });
      await dialog.getByRole("button", { name: "Handwerk schließen", exact: true }).click();
      const environmentReadback = await assetEvidence();
      await page.reload();
      const persisted = await rpc<PlayerUiReadback>(page, "player.ui");
      expect(persisted.settings.hotbar[0]).toBe("9"); expect(persisted.settings.autoLoot).toBe(false);
      expect(persisted.equipment).toEqual([]); expect(persisted.items.find(i => i.id === item.id)?.status).toBe("owned");
      expect(errors).toEqual([]);
      await info.attach("ax1-real-readback", { body: JSON.stringify({ revision: process.env.AURION_RELEASE_SHA, userId, viewport, qualification: group.qualification, actions, animation, inventory: persisted, environment: environmentReadback, crafting, auth: "public_registration", earnedItems: loot.items, explicitIsolatedFixtures: { purpose: "normal_auto_loot_rare_pickup_crafting", drops: fixtureDrops } }), contentType: "application/json" });
    } finally { await page.close(); await pool.end(); }
  });
}
