import * as THREE from 'three';
import { LootDropEntity, RPGItem } from '../types';
interface LootVisual { entity: LootDropEntity; group: THREE.Group; beacon: THREE.Mesh; orb: THREE.Mesh; light: THREE.PointLight; }
export class LootDropManager {
  public scene:THREE.Scene; public lootDrops:LootVisual[]=[]; private dropCounter=0;
  constructor(scene:THREE.Scene){this.scene=scene;}
  public spawnLoot(item:RPGItem,x:number,z:number,goldAmount:number=0):LootDropEntity{const id=`loot_${++this.dropCounter}`,rarity=item.rarity;let colorHex=0xffffff;if(rarity==='uncommon')colorHex=0x22c55e;else if(rarity==='rare')colorHex=0x3b82f6;else if(rarity==='epic')colorHex=0xa855f7;else if(rarity==='legendary')colorHex=0xf59e0b;const group=new THREE.Group();group.position.set(x,0,z);const orb=new THREE.Mesh(new THREE.OctahedronGeometry(.4,0),new THREE.MeshStandardMaterial({color:colorHex,emissive:colorHex,emissiveIntensity:1.5,roughness:.1}));orb.position.y=.8;group.add(orb);const beacon=new THREE.Mesh(new THREE.CylinderGeometry(.12,.4,12,8,1,true),new THREE.MeshBasicMaterial({color:colorHex,transparent:true,opacity:.45,side:THREE.DoubleSide,blending:THREE.AdditiveBlending}));beacon.position.y=6;group.add(beacon);const poolGeo=new THREE.CircleGeometry(1.2,16);poolGeo.rotateX(-Math.PI/2);const pool=new THREE.Mesh(poolGeo,new THREE.MeshBasicMaterial({color:colorHex,transparent:true,opacity:.5}));pool.position.y=.05;group.add(pool);const light=new THREE.PointLight(colorHex,1.2,8);light.position.set(0,1.2,0);group.add(light);this.scene.add(group);const entity={id,item,x,y:0,z,goldAmount,rarity,beamColor:`#${colorHex.toString(16).padStart(6,'0')}`,spawnTime:Date.now()};this.lootDrops.push({entity,group,beacon,orb,light});return entity;}
  public update(delta:number){this.lootDrops.forEach(loot=>{loot.orb.rotation.y+=delta*2.5;loot.orb.rotation.x+=delta*1.2;loot.orb.position.y=.8+Math.sin(Date.now()*.004)*.18;loot.beacon.rotation.y+=delta*.8;});}
  public removeLoot(lootId:string){const i=this.lootDrops.findIndex(l=>l.entity.id===lootId);if(i!==-1){this.scene.remove(this.lootDrops[i].group);this.lootDrops.splice(i,1);}}
  public getNearbyLoot(playerX:number,playerZ:number,pickupRadius:number=3.5){for(const loot of this.lootDrops)if(Math.hypot(loot.entity.x-playerX,loot.entity.z-playerZ)<=pickupRadius)return loot.entity;return null;}
  public getAllDrops(){return this.lootDrops.map(l=>l.entity);}
}
