import { DeterministicSimulation } from "@shared/deterministicSimulation";
import { validConfirmedZoneMobs, type ConfirmedZoneMob, type ZoneMobArchetype } from "@shared/zoneMobContract";
import * as THREE from 'three';
import type { RPGItem, WorldMobEntity } from '../types';
import { RPG_ITEMS_DATABASE } from '../data/mmorpgData';
import type { LootDropManager } from './LootDropManager';

type MobVisual={data:WorldMobEntity;group:THREE.Group;body:THREE.Mesh;hpBar:THREE.Mesh};
const mobNames:Readonly<Record<ZoneMobArchetype,string>>=Object.freeze({clockwork_stalker:'Clockwork Stalker',corrupted_golem:'Corrupted Golem',aether_wisp:'Aether Wisp',steam_drake:'Steam Drake',centurion_elite:'Brass Centurion',titan_boss:'The Aether Titan'});

export class MobManager{
  public readonly scene:THREE.Scene;public mobs:MobVisual[]=[];private counter=0;private lootManager?:LootDropManager;private serverAuthority=false;private confirmedSnapshot=false;
  constructor(scene:THREE.Scene,lootManager:LootDropManager,private readonly simulation:DeterministicSimulation){this.scene=scene;this.lootManager=lootManager;this.spawnInitial();}
  public get isServerAuthoritative():boolean{return this.serverAuthority;}
  public get hasConfirmedSnapshot():boolean{return this.confirmedSnapshot;}
  private dropTable(level:number):RPGItem[]{return RPG_ITEMS_DATABASE.filter(item=>item.levelReq<=Math.max(1,level+1)).slice(0,8);}
  private visualFor(data:WorldMobEntity):MobVisual{const group=new THREE.Group();const material=new THREE.MeshStandardMaterial({color:new THREE.Color(data.color),metalness:0.62,roughness:0.38,emissive:new THREE.Color(data.color),emissiveIntensity:data.isBoss?0.35:0.08});const body=new THREE.Mesh(data.isBoss?new THREE.DodecahedronGeometry(1.7,1):new THREE.CapsuleGeometry(0.55,1.05,4,7),material);body.position.y=data.isBoss?1.8:1.15;group.add(body);group.position.set(data.x,data.y,data.z);this.scene.add(group);const hpBar=new THREE.Mesh(new THREE.PlaneGeometry(data.isBoss?3.5:1.8,0.12),new THREE.MeshBasicMaterial({color:0x22c55e,side:THREE.DoubleSide}));hpBar.position.y=data.isBoss?4.2:2.6;group.add(hpBar);const visual={data,group,body,hpBar};this.mobs.push(visual);return visual;}
  private makeData(id:string,type:WorldMobEntity['type'],name:string,level:number,x:number,z:number,boss=false,elite=false):WorldMobEntity{const hp=(boss?360:elite?150:75)+level*18;return{id,name,type,level,hp,maxHp:hp,x,y:0,z,spawnX:x,spawnZ:z,radius:boss?1.8:0.75,attackRange:boss?5:2.2,damage:7+level*3,expReward:(boss?180:elite?65:28)+level*8,goldReward:(boss?95:elite?35:12)+level*3,isAggroed:false,isBoss:boss,isElite:elite,patrolAngle:this.serverAuthority?0:this.simulation.random("mob:patrol")*Math.PI*2,attackCooldown:0,maxAttackCooldown:boss?2.8:1.8,dropTable:this.dropTable(level),color:boss?'#f97316':elite?'#a855f7':'#ef4444'};}
  private create(type:WorldMobEntity['type'],name:string,level:number,x:number,z:number,boss=false,elite=false):WorldMobEntity{const data=this.makeData(`mob_${++this.counter}`,type,name,level,x,z,boss,elite);this.visualFor(data);return data;}
  private spawnInitial():void{const definitions:[WorldMobEntity['type'],string,number,number,number,boolean?,boolean?][]=[['clockwork_stalker','Clockwork Stalker',1,18,-18],['aether_wisp','Aether Wisp',2,34,-28],['corrupted_golem','Corrupted Golem',3,-34,-20,false,true],['steam_drake','Steam Drake',4,-48,28,false,true],['centurion_elite','Brass Centurion',5,28,42,false,true],['titan_boss','The Aether Titan',8,0,68,true,true]];definitions.forEach(def=>this.create(...def));for(let index=0;index<10;index++)this.create(index%2?'clockwork_stalker':'aether_wisp',index%2?'Clockwork Stalker':'Aether Wisp',1+index%4,-55+index*11,-50+index%3*22);}
  /**
   * AX1-first cutover: preserve the authored world presentation while disabling
   * local mob truth. Until the first confirmed snapshot arrives these visuals
   * are scenery only: visible, but not targetable and never allowed to deal or
   * receive authoritative damage, mint loot or progress gameplay.
   */
  public enableServerAuthority():void{if(this.serverAuthority)return;this.serverAuthority=true;this.confirmedSnapshot=false;for(const mob of this.mobs){mob.data.isAggroed=false;mob.group.userData.aurionMobState="awaiting-confirmation";mob.group.userData.aurionTargetEntityId=null;mob.group.userData.aurionConfirmedMob=false;}}
  public applyAuthoritativeSnapshot(snapshot:readonly ConfirmedZoneMob[]):void{
    if(!validConfirmedZoneMobs(snapshot))throw new Error("ZONE_MOB_SNAPSHOT_INVALID");this.enableServerAuthority();this.confirmedSnapshot=true;const incoming=new Set(snapshot.map(mob=>mob.entityId));
    for(const visual of [...this.mobs])if(!incoming.has(visual.data.id)){this.scene.remove(visual.group);this.mobs.splice(this.mobs.indexOf(visual),1);}
    for(const mob of snapshot){const x=mob.position.x/1_000,z=mob.position.z/1_000;let visual=this.mobs.find(candidate=>candidate.data.id===mob.entityId);if(!visual)visual=this.visualFor(this.makeData(mob.entityId,mob.archetype,mobNames[mob.archetype],mob.level,x,z,mob.isBoss,mob.isElite));visual.data.level=mob.level;visual.data.hp=mob.health;visual.data.maxHp=mob.maxHealth;visual.data.x=x;visual.data.z=z;visual.data.spawnX=x;visual.data.spawnZ=z;visual.data.isAggroed=mob.state==="combat";visual.group.position.set(x,visual.data.y,z);visual.group.visible=mob.health>0;visual.hpBar.scale.x=Math.max(0.02,mob.health/mob.maxHealth);visual.group.userData.aurionMobState=mob.state;visual.group.userData.aurionTargetEntityId=mob.targetEntityId;visual.group.userData.aurionConfirmedMob=true;}
  }
  public authoritativeEvidence():readonly Readonly<{entityId:string;state:string;targetEntityId:string|null;x:number;z:number;health:number;maxHealth:number}>[]{if(!this.serverAuthority||!this.confirmedSnapshot)return Object.freeze([]);return Object.freeze(this.mobs.filter(mob=>mob.group.userData.aurionConfirmedMob===true).map(mob=>Object.freeze({entityId:mob.data.id,state:String(mob.group.userData.aurionMobState??"unknown"),targetEntityId:typeof mob.group.userData.aurionTargetEntityId==="string"?mob.group.userData.aurionTargetEntityId:null,x:mob.data.x,z:mob.data.z,health:mob.data.hp,maxHealth:mob.data.maxHp})).sort((a,b)=>a.entityId<b.entityId?-1:a.entityId>b.entityId?1:0));}
  public presentationEvidence():Readonly<{serverAuthority:boolean;confirmedSnapshot:boolean;visible:number;confirmed:number;awaiting:number}>{return Object.freeze({serverAuthority:this.serverAuthority,confirmedSnapshot:this.confirmedSnapshot,visible:this.mobs.filter(mob=>mob.group.visible).length,confirmed:this.mobs.filter(mob=>mob.group.userData.aurionConfirmedMob===true).length,awaiting:this.mobs.filter(mob=>mob.group.userData.aurionConfirmedMob!==true).length});}
  public update(delta:number,playerOrX:{x:number;z:number}|number,playerZ?:number,onAttack?:(mob:WorldMobEntity,damage:number)=>void):void{if(this.serverAuthority){for(const mob of this.mobs){mob.body.rotation.y+=delta*(mob.data.isBoss?0.35:0.75);mob.hpBar.scale.x=Math.max(0.02,mob.data.hp/mob.data.maxHp);}return;}const player=typeof playerOrX==='number'?{x:playerOrX,z:playerZ??0}:playerOrX;for(const mob of this.mobs){if(mob.data.hp<=0)continue;mob.data.attackCooldown=Math.max(0,mob.data.attackCooldown-delta);const dx=player.x-mob.data.x,dz=player.z-mob.data.z,distance=Math.hypot(dx,dz);mob.data.isAggroed=distance<(mob.data.isBoss?22:12);if(mob.data.isAggroed&&distance>mob.data.attackRange){const speed=(mob.data.isBoss?1.5:2.1)*delta;mob.data.x+=dx/(distance||1)*speed;mob.data.z+=dz/(distance||1)*speed;}else if(mob.data.isAggroed&&distance<=mob.data.attackRange&&mob.data.attackCooldown<=0){mob.data.attackCooldown=mob.data.maxAttackCooldown;onAttack?.(mob.data,mob.data.damage);}else if(!mob.data.isAggroed){mob.data.patrolAngle+=delta*0.35;mob.data.x=mob.data.spawnX+Math.cos(mob.data.patrolAngle)*2.2;mob.data.z=mob.data.spawnZ+Math.sin(mob.data.patrolAngle)*2.2;}mob.group.position.set(mob.data.x,mob.data.y,mob.data.z);mob.body.rotation.y+=delta*(mob.data.isBoss?0.35:0.75);mob.hpBar.scale.x=Math.max(0.02,mob.data.hp/mob.data.maxHp);}}
  public getNearbyMobs(x:number,z:number,radius=18):WorldMobEntity[]{if(this.serverAuthority&&!this.confirmedSnapshot)return[];return this.mobs.filter(mob=>mob.data.hp>0&&(!this.serverAuthority||mob.group.userData.aurionConfirmedMob===true)&&Math.hypot(mob.data.x-x,mob.data.z-z)<=radius).map(mob=>mob.data).sort((a,b)=>Math.hypot(a.x-x,a.z-z)-Math.hypot(b.x-x,b.z-z));}
  public nearest(x:number,z:number,max=18):WorldMobEntity|null{return this.getNearbyMobs(x,z,max)[0]??null;}
  public cycle(currentId:string|undefined,x:number,z:number):WorldMobEntity|null{const alive=this.getNearbyMobs(x,z,Number.POSITIVE_INFINITY);if(!alive.length)return null;const index=alive.findIndex(mob=>mob.id===currentId);return alive[(index+1)%alive.length];}
  public damageMob(mobId:string,amount:number):{mob:WorldMobEntity|null;isKilled:boolean}{if(this.serverAuthority)return{mob:null,isKilled:false};const visual=this.mobs.find(mob=>mob.data.id===mobId);if(!visual||visual.data.hp<=0)return{mob:null,isKilled:false};visual.data.hp=Math.max(0,visual.data.hp-Math.max(0,amount));const isKilled=visual.data.hp<=0;if(isKilled){visual.group.visible=false;const drop=visual.data.dropTable[Math.floor(this.simulation.random("mob:loot")*Math.max(1,visual.data.dropTable.length))];if(drop&&this.lootManager)this.lootManager.spawnLoot({...drop,stats:{...drop.stats}},visual.data.x,visual.data.z,visual.data.goldReward);}return{mob:visual.data,isKilled};}
  public damage(mobId:string,amount:number){return this.damageMob(mobId,amount);}
  public spawnCustomMob(type:WorldMobEntity['type'],x:number,z:number):WorldMobEntity{if(this.serverAuthority)throw new Error("SERVER_MOB_AUTHORITY_REQUIRED");const boss=type==='titan_boss';const elite=boss||type==='centurion_elite'||type==='corrupted_golem'||type==='steam_drake';const level=boss?8:elite?5:2;return this.create(type,mobNames[type],level,x,z,boss,elite);}
  public dispose():void{this.mobs.forEach(mob=>this.scene.remove(mob.group));this.mobs=[];}
}
