import { DeterministicSimulation } from "@shared/deterministicSimulation";
import * as THREE from 'three';
import { CharacterClassId, SimulatedPlayer } from '../types';
import { MMORPG_CLASSES } from '../data/mmorpgData';
export class SimulatedRealmPlayers {
  public scene:THREE.Scene; public players:{data:SimulatedPlayer;group:THREE.Group}[]=[];
  constructor(scene:THREE.Scene, private readonly simulation: DeterministicSimulation){this.scene=scene;this.spawnRealmAdventurers();}
  private spawnRealmAdventurers(){const adventurers=[{name:'Sir_Galahad_99',classId:'knight' as CharacterClassId,guild:'<Iron Dawn>',x:-8,z:-10},{name:'ArcaneLilly',classId:'mage' as CharacterClassId,guild:'<Chrono Order>',x:12,z:-8},{name:'ShadowStrike_X',classId:'ranger' as CharacterClassId,guild:'<Silent Fang>',x:42,z:-32},{name:'SteamMechanic_Gabe',classId:'engineer' as CharacterClassId,guild:'<Cog Syndicate>',x:-35,z:-14},{name:'Valkyrie_Aurora',classId:'knight' as CharacterClassId,guild:'<Iron Dawn>',x:60,z:-48},{name:'VoidWalker_Null',classId:'mage' as CharacterClassId,guild:'<Eclipse>',x:2,z:45}];adventurers.forEach((adv,i)=>{const def=MMORPG_CLASSES[adv.classId],group=new THREE.Group();group.position.set(adv.x,0,adv.z);const mat=new THREE.MeshStandardMaterial({color:new THREE.Color(def.color),metalness:.7,roughness:.3});const body=new THREE.Mesh(new THREE.BoxGeometry(.8,1.2,.5),mat);body.position.y=1.2;group.add(body);const head=new THREE.Mesh(new THREE.BoxGeometry(.5,.5,.5),mat);head.position.y=2;group.add(head);const weapon=new THREE.Mesh(new THREE.BoxGeometry(.15,1.4,.1),mat);weapon.position.set(.6,1.2,.3);group.add(weapon);this.scene.add(group);this.players.push({data:{id:`sim_player_${i}`,name:adv.name,className:def.name,classId:adv.classId,level:4+Math.floor(this.simulation.random("simulated-players")*8),x:adv.x,y:0,z:adv.z,action:'patrolling',guildTag:adv.guild},group});});}
  public update(delta:number){this.players.forEach(p=>{p.data.x+=Math.sin(this.simulation.elapsedMilliseconds*.001+parseInt(p.data.id.slice(-1)))*2.5*delta;p.data.z+=Math.cos(this.simulation.elapsedMilliseconds*.0012+parseInt(p.data.id.slice(-1)))*2.5*delta;p.group.position.set(p.data.x,0,p.data.z);p.group.rotation.y+=delta*.6;});}
  public getPlayers(){return this.players.map(p=>p.data);}
  public dispose(){const geometries=new Set<THREE.BufferGeometry>(),materials=new Set<THREE.Material>();for(const player of this.players){this.scene.remove(player.group);player.group.traverse(object=>{if(object instanceof THREE.Mesh){geometries.add(object.geometry);for(const material of Array.isArray(object.material)?object.material:[object.material])materials.add(material);}});}geometries.forEach(value=>value.dispose());materials.forEach(value=>value.dispose());this.players=[];}
}
