import { isBaseChunkRoadTile, WORLD_CHUNK_GRID_SIZE, type BaseWorldChunk, type ChunkSurface } from "./worldChunkProtocol";

/**
 * Pure deterministic design/oracle helpers for Echoes of Aurion.
 *
 * Authority boundary:
 * - Aurion owns gameplay/world state and deterministic local calculation.
 * - Wolfram CAG may independently recompute bounded formulas/invariants.
 * - CAG output never mutates XP, chunks, collision, loot, persistence, or GLB bytes.
 *
 * This module intentionally does not implement a second terrain generator. Terrain probes
 * are derived from the canonical BaseWorldChunk generated by worldChunkProtocol.ts.
 */
export const AURION_CAG_DESIGN_PROTOCOL_VERSION = "aurion.cag-design-oracle.v1" as const;

const ZERO = 0n;
const ONE = 1n;
const TWO = 2n;
const FIVE = 5n;
const SEVEN = 7n;
const FIFTY = 50n;
const SCALE_E8 = 100_000_000;

function parseCanonicalUnsigned(value: string, field: string): bigint {
  if (!/^(0|[1-9][0-9]*)$/.test(value)) throw new Error(`${field} must be a canonical unsigned decimal`);
  return BigInt(value);
}

function exactPower(base: bigint, exponent: bigint): bigint {
  let result = ONE;
  for (let index = ZERO; index < exponent; index += ONE) result *= base;
  return result;
}

function nthRootFloor(value: bigint, degree: bigint): bigint {
  if (value < TWO) return value;
  let low = ZERO;
  let high = ONE;
  while (exactPower(high, degree) <= value) high *= TWO;
  while (low + ONE < high) {
    const mid = (low + high) / TWO;
    if (exactPower(mid, degree) <= value) low = mid;
    else high = mid;
  }
  return low;
}

/** Independent exact reproduction of floor(50 * level^(7/5)). No level cap and no float drift. */
export function cagOracleXpForNextLevelExact(levelExact: string): string {
  const parsed = parseCanonicalUnsigned(levelExact, "levelExact");
  const level = parsed < ONE ? ONE : parsed;
  return nthRootFloor(exactPower(FIFTY, FIVE) * exactPower(level, SEVEN), FIVE).toString(10);
}

export type AurionCagProbe = Readonly<{
  kind: "progression" | "terrain_invariants" | "model_scale" | "terrain_texturization" | "terrain_continuity";
  code: string;
  expectedExact: string;
  truthNotice: string;
}>;

export function buildProgressionCagProbe(levelExact: string): AurionCagProbe {
  const level = parseCanonicalUnsigned(levelExact, "levelExact");
  const safe = level < ONE ? ONE : level;
  const expectedExact = cagOracleXpForNextLevelExact(safe.toString(10));
  return Object.freeze({
    kind: "progression",
    code: `Floor[50*(${safe.toString(10)})^(7/5)]`,
    expectedExact,
    truthNotice: "CAG independently recomputes one exact progression threshold; Aurion remains progression authority.",
  });
}

export type AurionTerrainInvariantSummary = Readonly<{
  tileCount: number;
  roadTileCount: number;
  minHeightMm: number;
  maxHeightMm: number;
  maxAdjacentDeltaMm: number;
}>;

function canonicalTerrainMatrix(chunk: BaseWorldChunk): readonly (readonly number[])[] {
  if (chunk.tiles.length !== WORLD_CHUNK_GRID_SIZE * WORLD_CHUNK_GRID_SIZE) {
    throw new Error("terrain tile count does not match the canonical world chunk grid");
  }
  const byCoordinate = new Map<string, number>();
  for (const tile of chunk.tiles) {
    if (!Number.isSafeInteger(tile.x) || !Number.isSafeInteger(tile.z) || !Number.isSafeInteger(tile.heightMm)) {
      throw new Error("terrain tile must use integer coordinates and millimeter heights");
    }
    if (tile.x < 0 || tile.x >= WORLD_CHUNK_GRID_SIZE || tile.z < 0 || tile.z >= WORLD_CHUNK_GRID_SIZE) {
      throw new Error("terrain tile coordinate is outside the canonical chunk grid");
    }
    const key = `${tile.x}:${tile.z}`;
    if (byCoordinate.has(key)) throw new Error("terrain tile coordinate must be unique");
    byCoordinate.set(key, tile.heightMm);
  }
  return Object.freeze(Array.from({ length: WORLD_CHUNK_GRID_SIZE }, (_, z) =>
    Object.freeze(Array.from({ length: WORLD_CHUNK_GRID_SIZE }, (_, x) => {
      const value = byCoordinate.get(`${x}:${z}`);
      if (value === undefined) throw new Error("terrain grid is incomplete");
      return value;
    })),
  ));
}

export function summarizeWorldChunkTerrain(chunk: BaseWorldChunk): AurionTerrainInvariantSummary {
  const matrix = canonicalTerrainMatrix(chunk);
  const values = matrix.flat();
  let maxAdjacentDeltaMm = 0;
  for (let z = 0; z < matrix.length; z += 1) {
    for (let x = 0; x < matrix[z]!.length; x += 1) {
      const current = matrix[z]![x]!;
      if (x + 1 < matrix[z]!.length) {
        maxAdjacentDeltaMm = Math.max(maxAdjacentDeltaMm, Math.abs(current - matrix[z]![x + 1]!));
      }
      if (z + 1 < matrix.length) {
        maxAdjacentDeltaMm = Math.max(maxAdjacentDeltaMm, Math.abs(current - matrix[z + 1]![x]!));
      }
    }
  }
  return Object.freeze({
    tileCount: chunk.tiles.length,
    roadTileCount: chunk.tiles.filter(isBaseChunkRoadTile).length,
    minHeightMm: Math.min(...values),
    maxHeightMm: Math.max(...values),
    maxAdjacentDeltaMm,
  });
}

/**
 * Recomputes only geometry statistics from the already-authoritative Aurion chunk.
 * CAG does not choose the seed, biome, surfaces, resources or gameplay state.
 */
export function buildWorldChunkTerrainCagProbe(chunk: BaseWorldChunk): AurionCagProbe {
  const matrix = canonicalTerrainMatrix(chunk);
  const summary = summarizeWorldChunkTerrain(chunk);
  const rows = matrix.map(row => `{${row.join(",")}}`).join(",");
  const code = [
    `m={${rows}}`,
    "dx=Abs[Differences[Transpose[m]]]",
    "dz=Abs[Differences[m]]",
    "{Min[m],Max[m],Max[dx,dz]}",
  ].join(";");
  return Object.freeze({
    kind: "terrain_invariants",
    code,
    expectedExact: `{${summary.minHeightMm},${summary.maxHeightMm},${summary.maxAdjacentDeltaMm}}`,
    truthNotice: "CAG checks bounded geometry statistics from a canonical Aurion chunk; it does not generate or mutate terrain authority.",
  });
}


export type AurionTerrainTexturizationSummary = Readonly<{
  totalTiles: number;
  grassTiles: number;
  riverbankTiles: number;
  stoneTiles: number;
  forestFloorTiles: number;
  ashTiles: number;
  ruinPathTiles: number;
}>;

export function summarizeWorldChunkTexturization(chunk: BaseWorldChunk): AurionTerrainTexturizationSummary {
  canonicalSurfaceMatrix(chunk);
  let grass = 0, riverbank = 0, stone = 0, forestFloor = 0, ash = 0, ruinPath = 0;
  for (const tile of chunk.tiles) {
    if (tile.surface === "grass") grass++;
    else if (tile.surface === "riverbank") riverbank++;
    else if (tile.surface === "stone") stone++;
    else if (tile.surface === "forest_floor") forestFloor++;
    else if (tile.surface === "ash") ash++;
    else if (tile.surface === "ruin_path") ruinPath++;
  }
  return Object.freeze({
    totalTiles: chunk.tiles.length,
    grassTiles: grass,
    riverbankTiles: riverbank,
    stoneTiles: stone,
    forestFloorTiles: forestFloor,
    ashTiles: ash,
    ruinPathTiles: ruinPath,
  });
}

/**
 * Recomputes and verifies the deterministic texture/material distribution of an authoritative chunk.
 * CAG evaluates surface material counts without mutating world data.
 */
export function buildTerrainTexturizationCagProbe(chunk: BaseWorldChunk): AurionCagProbe {
  const summary = summarizeWorldChunkTexturization(chunk);
  const surfaces = chunk.tiles.map(t => {
    switch(t.surface) {
        case "grass": return 1;
        case "riverbank": return 2;
        case "stone": return 3;
        case "forest_floor": return 4;
        case "ash": return 5;
        case "ruin_path": return 6;
        default: throw new Error(`unmapped surface: ${t.surface}`);
    }
  }).join(",");
  const code = [
    `surfaces={${surfaces}}`,
    `{Length[surfaces], Count[surfaces, 1], Count[surfaces, 2], Count[surfaces, 3], Count[surfaces, 4], Count[surfaces, 5], Count[surfaces, 6]}`
  ].join(";");

  return Object.freeze({
    kind: "terrain_texturization",
    code,
    expectedExact: `{${summary.totalTiles},${summary.grassTiles},${summary.riverbankTiles},${summary.stoneTiles},${summary.forestFloorTiles},${summary.ashTiles},${summary.ruinPathTiles}}`,
    truthNotice: "CAG verifies texturization distribution of a canonical Aurion chunk; it does not assign textures or modify world state.",
  });
}



const SURFACE_MAPPING: Record<ChunkSurface, number> = {
  grass: 1,
  forest_floor: 2,
  riverbank: 3,
  stone: 4,
  ash: 5,
  ruin_path: 6,
};

export type AurionTerrainContinuitySummary = Readonly<{
  varianceMm2: number;
  surfaceTransitions: number;
}>;

function canonicalSurfaceMatrix(chunk: BaseWorldChunk): readonly (readonly number[])[] {
  if (chunk.tiles.length !== WORLD_CHUNK_GRID_SIZE * WORLD_CHUNK_GRID_SIZE) {
    throw new Error("terrain tile count does not match the canonical world chunk grid");
  }
  const byCoordinate = new Map<string, number>();
  for (const tile of chunk.tiles) {
    if (!Number.isSafeInteger(tile.x) || !Number.isSafeInteger(tile.z) || !Number.isSafeInteger(tile.heightMm)) {
      throw new Error("terrain tile must use integer coordinates and millimeter heights");
    }
    if (tile.x < 0 || tile.x >= WORLD_CHUNK_GRID_SIZE || tile.z < 0 || tile.z >= WORLD_CHUNK_GRID_SIZE) {
      throw new Error("terrain tile coordinate is outside the canonical chunk grid");
    }
    const key = `${tile.x}:${tile.z}`;
    if (byCoordinate.has(key)) throw new Error("terrain tile coordinate must be unique");
    const mapped = SURFACE_MAPPING[tile.surface];
    if (!Number.isSafeInteger(mapped)) throw new Error(`unmapped surface: ${tile.surface}`);
    byCoordinate.set(key, mapped);
  }
  return Object.freeze(Array.from({ length: WORLD_CHUNK_GRID_SIZE }, (_, z) =>
    Object.freeze(Array.from({ length: WORLD_CHUNK_GRID_SIZE }, (_, x) => {
      const value = byCoordinate.get(`${x}:${z}`);
      if (value === undefined) throw new Error("terrain grid is incomplete");
      return value;
    })),
  ));
}

export function summarizeWorldChunkTerrainContinuity(chunk: BaseWorldChunk): AurionTerrainContinuitySummary {
  const heightMatrix = canonicalTerrainMatrix(chunk);
  const surfaceMatrix = canonicalSurfaceMatrix(chunk);
  const heights = heightMatrix.flat();

  // Exact sample variance, rounded to nearest integer with ties to even, as in Wolfram Round.
  // Integer arithmetic also avoids cancellation for large, safe-integer heights.
  const count = BigInt(heights.length);
  const sum = heights.reduce((total, height) => total + BigInt(height), 0n);
  const squares = heights.reduce((total, height) => total + BigInt(height) ** 2n, 0n);
  const numerator = count * squares - sum * sum;
  const denominator = count * (count - 1n);
  const quotient = numerator / denominator;
  const doubledRemainder = 2n * (numerator % denominator);
  const rounded = quotient + (doubledRemainder > denominator ||
    (doubledRemainder === denominator && quotient % 2n === 1n) ? 1n : 0n);
  const varianceMm2 = Number(rounded);
  if (!Number.isSafeInteger(varianceMm2)) throw new Error("terrain variance exceeds safe integer range");

  // Transitions
  let surfaceTransitions = 0;
  for (let z = 0; z < WORLD_CHUNK_GRID_SIZE; z += 1) {
    for (let x = 0; x < WORLD_CHUNK_GRID_SIZE; x += 1) {
      const current = surfaceMatrix[z]![x]!;
      if (x + 1 < WORLD_CHUNK_GRID_SIZE && current !== surfaceMatrix[z]![x + 1]!) {
        surfaceTransitions += 1;
      }
      if (z + 1 < WORLD_CHUNK_GRID_SIZE && current !== surfaceMatrix[z + 1]![x]!) {
        surfaceTransitions += 1;
      }
    }
  }

  return Object.freeze({
    varianceMm2,
    surfaceTransitions,
  });
}

/**
 * Recomputes geometry variance and material continuity from the already-authoritative Aurion chunk.
 */
export function buildWorldChunkTerrainContinuityCagProbe(chunk: BaseWorldChunk): AurionCagProbe {
  const heightMatrix = canonicalTerrainMatrix(chunk);
  const surfaceMatrix = canonicalSurfaceMatrix(chunk);
  const summary = summarizeWorldChunkTerrainContinuity(chunk);

  const hRows = heightMatrix.map(row => `{${row.join(",")}}`).join(",");
  const sRows = surfaceMatrix.map(row => `{${row.join(",")}}`).join(",");

  const code = [
    `h={${hRows}}`,
    `s={${sRows}}`,
    "var=Round[Variance[Flatten[h]]]",
    "sdx=Flatten[Differences[Transpose[s]]]",
    "sdz=Flatten[Differences[s]]",
    "trans=Count[sdx,x_/;x!=0]+Count[sdz,x_/;x!=0]",
    "{var,trans}"
  ].join(";");

  return Object.freeze({
    kind: "terrain_continuity",
    code,
    expectedExact: `{${summary.varianceMm2},${summary.surfaceTransitions}}`,
    truthNotice: "CAG independently computes terrain variance and material continuity constraints; it does not generate texturization.",
  });
}
export type ModelBounds = Readonly<{
  min: readonly [number, number, number];
  max: readonly [number, number, number];
}>;

export type ModelScaleNormalization = Readonly<{
  sourceExtents: readonly [number, number, number];
  sourceMaxExtent: number;
  targetMaxExtent: number;
  scaleE8: number;
  scale: number;
  normalizedExtents: readonly [number, number, number];
}>;

export const WORLD_ASSET_TARGET_MAX_EXTENT: Readonly<Record<string, number>> = Object.freeze({
  building: 11,
  structure: 8,
  prop: 2,
  tree: 7,
  mountain: 18,
  rock: 2,
  plant: 1,
});

function finitePositive(value: number, field: string): number {
  if (!Number.isFinite(value) || value <= 0) throw new Error(`${field} must be a positive finite number`);
  return value;
}

export function normalizeModelBounds(bounds: ModelBounds, targetMaxExtent: number): ModelScaleNormalization {
  finitePositive(targetMaxExtent, "targetMaxExtent");
  const extents = bounds.max.map((value, index) => value - bounds.min[index]!) as [number, number, number];
  extents.forEach((value, index) => finitePositive(value, `extent${index}`));
  const sourceMaxExtent = Math.max(...extents);
  const scaleE8 = Math.round((targetMaxExtent / sourceMaxExtent) * SCALE_E8);
  if (!Number.isSafeInteger(scaleE8) || scaleE8 <= 0) throw new Error("normalized model scale is outside the safe integer envelope");
  const scale = scaleE8 / SCALE_E8;
  return Object.freeze({
    sourceExtents: Object.freeze(extents),
    sourceMaxExtent,
    targetMaxExtent,
    scaleE8,
    scale,
    normalizedExtents: Object.freeze(extents.map(value => value * scale) as [number, number, number]),
  });
}

export function normalizeWorldAssetBounds(category: string, bounds: ModelBounds): ModelScaleNormalization {
  const target = WORLD_ASSET_TARGET_MAX_EXTENT[category];
  if (target === undefined) throw new Error(`unsupported world asset category: ${category}`);
  return normalizeModelBounds(bounds, target);
}

function wolframNumber(value: number): string {
  if (!Number.isFinite(value)) throw new Error("Wolfram probe values must be finite");
  return Number.isInteger(value) ? String(value) : value.toPrecision(17);
}

export function buildModelScaleCagProbe(bounds: ModelBounds, targetMaxExtent: number): AurionCagProbe {
  const normalized = normalizeModelBounds(bounds, targetMaxExtent);
  const extents = normalized.sourceExtents.map(wolframNumber).join(",");
  return Object.freeze({
    kind: "model_scale",
    code: `source=Max[{${extents}}];Round[(${wolframNumber(targetMaxExtent)}/source)*100000000]`,
    expectedExact: String(normalized.scaleE8),
    truthNotice: "CAG verifies a bounded presentation-scale calculation; applying a transform remains an explicit Aurion asset-authoring decision.",
  });
}

export function buildWorldAssetScaleCagProbe(category: string, bounds: ModelBounds): AurionCagProbe {
  const target = WORLD_ASSET_TARGET_MAX_EXTENT[category];
  if (target === undefined) throw new Error(`unsupported world asset category: ${category}`);
  return buildModelScaleCagProbe(bounds, target);
}
