import { isBaseChunkRoadTile, WORLD_CHUNK_GRID_SIZE, type BaseWorldChunk } from "./worldChunkProtocol";

/**
 * Pure deterministic design/oracle helpers for Echoes of Aurion.
 *
 * Authority boundary:
 * - Aurion owns gameplay/world state and deterministic local calculation.
 * - Wolfram CAG may independently recompute bounded formulas/invariants.
 * - CAG output never mutates XP, chunks, collision, loot, persistence, or GLB bytes.
 *
 * This module intentionally does not implement a second terrain generator. Terrain probes
 * are derived from the canonical BaseWorldChunk generated by worldChunkProtocol.ts.
 */
export const AURION_CAG_DESIGN_PROTOCOL_VERSION = "aurion.cag-design-oracle.v1" as const;

const ZERO = 0n;
const ONE = 1n;
const TWO = 2n;
const FIVE = 5n;
const SEVEN = 7n;
const FIFTY = 50n;
const SCALE_E8 = 100_000_000;

function parseCanonicalUnsigned(value: string, field: string): bigint {
  if (!/^(0|[1-9][0-9]*)$/.test(value)) throw new Error(`${field} must be a canonical unsigned decimal`);
  return BigInt(value);
}

function exactPower(base: bigint, exponent: bigint): bigint {
  let result = ONE;
  for (let index = ZERO; index < exponent; index += ONE) result *= base;
  return result;
}

function nthRootFloor(value: bigint, degree: bigint): bigint {
  if (value < TWO) return value;
  let low = ZERO;
  let high = ONE;
  while (exactPower(high, degree) <= value) high *= TWO;
  while (low + ONE < high) {
    const mid = (low + high) / TWO;
    if (exactPower(mid, degree) <= value) low = mid;
    else high = mid;
  }
  return low;
}

/** Independent exact reproduction of floor(50 * level^(7/5)). No level cap and no float drift. */
export function cagOracleXpForNextLevelExact(levelExact: string): string {
  const parsed = parseCanonicalUnsigned(levelExact, "levelExact");
  const level = parsed < ONE ? ONE : parsed;
  return nthRootFloor(exactPower(FIFTY, FIVE) * exactPower(level, SEVEN), FIVE).toString(10);
}

export type AurionCagProbe = Readonly<{
  kind: "progression" | "terrain_invariants" | "model_scale";
  code: string;
  expectedExact: string;
  truthNotice: string;
}>;

export function buildProgressionCagProbe(levelExact: string): AurionCagProbe {
  const level = parseCanonicalUnsigned(levelExact, "levelExact");
  const safe = level < ONE ? ONE : level;
  const expectedExact = cagOracleXpForNextLevelExact(safe.toString(10));
  return Object.freeze({
    kind: "progression",
    code: `Floor[50*(${safe.toString(10)})^(7/5)]`,
    expectedExact,
    truthNotice: "CAG independently recomputes one exact progression threshold; Aurion remains progression authority.",
  });
}

export type AurionTerrainInvariantSummary = Readonly<{
  tileCount: number;
  roadTileCount: number;
  minHeightMm: number;
  maxHeightMm: number;
  maxAdjacentDeltaMm: number;
}>;

function canonicalTerrainMatrix(chunk: BaseWorldChunk): readonly (readonly number[])[] {
  if (chunk.tiles.length !== WORLD_CHUNK_GRID_SIZE * WORLD_CHUNK_GRID_SIZE) {
    throw new Error("terrain tile count does not match the canonical world chunk grid");
  }
  const byCoordinate = new Map<string, number>();
  for (const tile of chunk.tiles) {
    if (!Number.isSafeInteger(tile.x) || !Number.isSafeInteger(tile.z) || !Number.isSafeInteger(tile.heightMm)) {
      throw new Error("terrain tile must use integer coordinates and millimeter heights");
    }
    if (tile.x < 0 || tile.x >= WORLD_CHUNK_GRID_SIZE || tile.z < 0 || tile.z >= WORLD_CHUNK_GRID_SIZE) {
      throw new Error("terrain tile coordinate is outside the canonical chunk grid");
    }
    const key = `${tile.x}:${tile.z}`;
    if (byCoordinate.has(key)) throw new Error("terrain tile coordinate must be unique");
    byCoordinate.set(key, tile.heightMm);
  }
  return Object.freeze(Array.from({ length: WORLD_CHUNK_GRID_SIZE }, (_, z) =>
    Object.freeze(Array.from({ length: WORLD_CHUNK_GRID_SIZE }, (_, x) => {
      const value = byCoordinate.get(`${x}:${z}`);
      if (value === undefined) throw new Error("terrain grid is incomplete");
      return value;
    })),
  ));
}

export function summarizeWorldChunkTerrain(chunk: BaseWorldChunk): AurionTerrainInvariantSummary {
  const matrix = canonicalTerrainMatrix(chunk);
  const values = matrix.flat();
  let maxAdjacentDeltaMm = 0;
  for (let z = 0; z < matrix.length; z += 1) {
    for (let x = 0; x < matrix[z]!.length; x += 1) {
      const current = matrix[z]![x]!;
      if (x + 1 < matrix[z]!.length) {
        maxAdjacentDeltaMm = Math.max(maxAdjacentDeltaMm, Math.abs(current - matrix[z]![x + 1]!));
      }
      if (z + 1 < matrix.length) {
        maxAdjacentDeltaMm = Math.max(maxAdjacentDeltaMm, Math.abs(current - matrix[z + 1]![x]!));
      }
    }
  }
  return Object.freeze({
    tileCount: chunk.tiles.length,
    roadTileCount: chunk.tiles.filter(isBaseChunkRoadTile).length,
    minHeightMm: Math.min(...values),
    maxHeightMm: Math.max(...values),
    maxAdjacentDeltaMm,
  });
}

/**
 * Recomputes only geometry statistics from the already-authoritative Aurion chunk.
 * CAG does not choose the seed, biome, surfaces, resources or gameplay state.
 */
export function buildWorldChunkTerrainCagProbe(chunk: BaseWorldChunk): AurionCagProbe {
  const matrix = canonicalTerrainMatrix(chunk);
  const summary = summarizeWorldChunkTerrain(chunk);
  const rows = matrix.map(row => `{${row.join(",")}}`).join(",");
  const code = [
    `m={${rows}}`,
    "flat=Flatten[m]",
    "dx=Flatten[Abs[Map[Differences,m]]]",
    "dz=Flatten[Abs[Differences[m]]]",
    "{Min[flat],Max[flat],Max[Join[dx,dz]]}",
  ].join(";");
  return Object.freeze({
    kind: "terrain_invariants",
    code,
    expectedExact: `{${summary.minHeightMm},${summary.maxHeightMm},${summary.maxAdjacentDeltaMm}}`,
    truthNotice: "CAG checks bounded geometry statistics from a canonical Aurion chunk; it does not generate or mutate terrain authority.",
  });
}

export type ModelBounds = Readonly<{
  min: readonly [number, number, number];
  max: readonly [number, number, number];
}>;

export type ModelScaleNormalization = Readonly<{
  sourceExtents: readonly [number, number, number];
  sourceMaxExtent: number;
  targetMaxExtent: number;
  scaleE8: number;
  scale: number;
  normalizedExtents: readonly [number, number, number];
}>;

export const WORLD_ASSET_TARGET_MAX_EXTENT: Readonly<Record<string, number>> = Object.freeze({
  building: 11,
  structure: 8,
  prop: 2,
  tree: 7,
  mountain: 18,
  rock: 2,
  plant: 1,
});

function finitePositive(value: number, field: string): number {
  if (!Number.isFinite(value) || value <= 0) throw new Error(`${field} must be a positive finite number`);
  return value;
}

export function normalizeModelBounds(bounds: ModelBounds, targetMaxExtent: number): ModelScaleNormalization {
  finitePositive(targetMaxExtent, "targetMaxExtent");
  const extents = bounds.max.map((value, index) => value - bounds.min[index]!) as [number, number, number];
  extents.forEach((value, index) => finitePositive(value, `extent${index}`));
  const sourceMaxExtent = Math.max(...extents);
  const scaleE8 = Math.round((targetMaxExtent / sourceMaxExtent) * SCALE_E8);
  if (!Number.isSafeInteger(scaleE8) || scaleE8 <= 0) throw new Error("normalized model scale is outside the safe integer envelope");
  const scale = scaleE8 / SCALE_E8;
  return Object.freeze({
    sourceExtents: Object.freeze(extents),
    sourceMaxExtent,
    targetMaxExtent,
    scaleE8,
    scale,
    normalizedExtents: Object.freeze(extents.map(value => value * scale) as [number, number, number]),
  });
}

export function normalizeWorldAssetBounds(category: string, bounds: ModelBounds): ModelScaleNormalization {
  const target = WORLD_ASSET_TARGET_MAX_EXTENT[category];
  if (target === undefined) throw new Error(`unsupported world asset category: ${category}`);
  return normalizeModelBounds(bounds, target);
}

function wolframNumber(value: number): string {
  if (!Number.isFinite(value)) throw new Error("Wolfram probe values must be finite");
  return Number.isInteger(value) ? String(value) : value.toPrecision(17);
}

export function buildModelScaleCagProbe(bounds: ModelBounds, targetMaxExtent: number): AurionCagProbe {
  const normalized = normalizeModelBounds(bounds, targetMaxExtent);
  const extents = normalized.sourceExtents.map(wolframNumber).join(",");
  return Object.freeze({
    kind: "model_scale",
    code: `source=Max[{${extents}}];Round[(${wolframNumber(targetMaxExtent)}/source)*100000000]`,
    expectedExact: String(normalized.scaleE8),
    truthNotice: "CAG verifies a bounded presentation-scale calculation; applying a transform remains an explicit Aurion asset-authoring decision.",
  });
}

export function buildWorldAssetScaleCagProbe(category: string, bounds: ModelBounds): AurionCagProbe {
  const target = WORLD_ASSET_TARGET_MAX_EXTENT[category];
  if (target === undefined) throw new Error(`unsupported world asset category: ${category}`);
  return buildModelScaleCagProbe(bounds, target);
}
